### ISSUE TITLE
Deleting a product or clearing the image cache leaves files hanging around

### ISSUE THREAD

**Issue by shopp-lighthouse-import** [ingenesis/shopp#1058]
*Imported from Lighthouse* http://shopp.lighthouseapp.com/projects/47561/tickets/1058
Reported by **Per Wiklander** at **Friday, 05-Aug-11 17:57:34 GMT-0400**

When I delete a product or use the ”Clear the image cache” button I would expect the actual files to disappear along with the meta entries in the DB. They are still there, presumably forever. This is regardless of using DBStorage or FSStorage.

###### Steps to Repeat ######

1. Create a product and upload some images
2. Delete the product
3. Check your image folder or the `wp_shopp_asset` table. The images are still there.

##### Environment ######
Server OS: **OSX**
Web Server: **Apache**
PHP version: **5.3.6**
WordPress Version: **3.1.2**
Shopp Version: **1.1.8**

**Comment by crunnells** [comment]
Closed as duplicate. See discussion in #2772
