### ISSUE TITLE
Add Sub-product Support

### ISSUE THREAD

**Issue by shopp-lighthouse-import** [ingenesis/shopp#13]
*Imported from Lighthouse* http://shopp.lighthouseapp.com/projects/47561/tickets/13
Reported by **Jonathan** at **Sunday, 07-Mar-10 23:20:56 GMT-0500**

There is a use-case where a merchant may wish to sell a product comprised of many parts (such as single songs of an album).  This has specific ramifications for downloadable goods.  In this scenario, purchasing the main product would essentially be a purchase for each sub-product with a collective price that overrides the individual price.  Downloads would be made available as separate sub-line-items.

This engineering could then provide the framework for product add-on options where add-ons would exist as sub-products that are part of a specific add-on option group.  (Computer HDDs for example)

**Comment by crunnells** [comment]
Closed as duplicate. See discussion in #40
