### ISSUE TITLE
Product images not removed after they are deleted

### ISSUE THREAD

**Issue by shopp-lighthouse-import** [ingenesis/shopp#1310]
*Imported from Lighthouse* http://shopp.lighthouseapp.com/projects/47561/tickets/1310
Reported by **Barry Hughes** at **Monday, 28-Nov-11 11:47:58 GMT-0500**

If a product image is deleted then the actual file remains on the file system (or the blob remains within the database).

It might be expected that the relevant file would be deleted - "this support ticket":https://shopplugin.net/support/topic/deleting-a-product-image-is-not-working refers.

###### Steps to Repeat ######

1. Add a product image
2. Save the product
3. Delete the product image
4. Save again
5. Inspect the filesystem/database, the asset is still present

##### Environment ######
Server OS: **Ubuntu 11.10/Windows 7**
Web Server: **Apache 2.2**
PHP version: **5.3.8**
WordPress Version: **3.2.1**
Shopp Version: **1.1.9**
Shopp Install: **fresh**

**Comment by crunnells** [comment]
Closed as duplicate. See discussion in #2772
