### ISSUE TITLE
Cart item promotions calculate incorrectly

### ISSUE THREAD

**Issue by shopp-lighthouse-import** [ingenesis/shopp#1492]
*Imported from Lighthouse* http://shopp.lighthouseapp.com/projects/47561/tickets/1492
Reported by **Clifton Griffin** at **Wednesday, 01-Feb-12 08:29:17 GMT-0500**

This is a problem in 1.1.9.1 as well as 1.2.

The following promotion is intended to discount $25 when one or more of the product is in the cart.   Instead, it discounts $25 for each of that item.  So adding 10 items results in a $250 discount.

http://grab.by/bKlq

I worked on this with Dave and we found that there doesn't seem to be a combination that allows us to achieve the desired effect.  We also confirmed it effects the current 1.2 build.

##### Environment ######
WordPress Version: **3.3.1**
Shopp Version: **1.2b RC3**

**Comment by jonathandavis** [comment]
The sequence described is feasible today. Closing this issue
