### ISSUE TITLE
Parent level taxrate not shared catagories beneath

### ISSUE THREAD

**Issue by shopp-lighthouse-import** [ingenesis/shopp#1939]
_Imported from Lighthouse_ http://shopp.lighthouseapp.com/projects/47561/tickets/1939
Reported by **Albert Boddema** at **Wednesday, 25-Jul-12 15:49:08 GMT-0400**

In my store I uses two taxrates, 6% for books and 19% for all other product.
When I asign the parent level 'books' to 6% taxrate the catagories beneath are not sharing that taxrate.
I have to assign the taxlevel to all the child levels. 

The response from Charles Griffin;
I'm fairly certain that is not the intended behavior. And if it is, it should be reevaluated.

Go ahead and file a bug ticket. Hopefully we can get it fixed in the next maintenance release.

Shopp Version: 1.2.3

**Comment by jonathandavis** [comment]
Instead of this being an enhancement, this is an un-handled case that should be treated as a bug. Moving to beta.

**Comment by Just-m** [comment]
I'd like to argue against changing this.
Taxes applied to a certain (child) category works the same way as products added to a (cihld) category.

When you have parent and child categories, products only added to the child do not show up in the parent category listing. The product only shows up in the parent category listing when the product is added to the parent as well as the child.

A taxrate setting with a product category name condition are only applied to products that are added to the named category.

Making these comparable system work in different ways only adds confusion.

For correct taxcalculations add the product to the parent as well as child category, or add taxrates to the to the child category.

**Comment by AlbertBoddema** [comment]
@Just-m I agree the way the tax rules are working now is the most flexibel option.
In 2013 this seemed stange to me because all books are by defauld 6% BTW.

**Comment by Just-m** [comment]
@AlbertBoddema thanks for your reply.
I'll close this topic for now.
