### ISSUE TITLE
Shopp Images Broken on Storefront Page on Nginx-powered websites

### ISSUE THREAD

**Issue by shopp-lighthouse-import** [ingenesis/shopp#2087]
*Imported from Lighthouse* http://shopp.lighthouseapp.com/projects/47561/tickets/2087
Reported by **Lorenzo Caum** at **Tuesday, 11-Dec-12 18:34:42 GMT-0500**

Images will appear to work everywhere except for on the storefront page on websites powered by nginx.

Workaround:

Modify api/theme/storefront.php to remove ".$img->filename" from about line 173.

**Comment by jonathandavis** [comment]
https://shopplugin.net/kb/nginx-rewrite-rule/
