### ISSUE TITLE
Inclusive Taxes and Shopp Donation Products results in No Taxes

### ISSUE THREAD

**Issue by shopp-lighthouse-import** [ingenesis/shopp#2132]
*Imported from Lighthouse* http://shopp.lighthouseapp.com/projects/47561/tickets/2132
Reported by **Lorenzo Caum** at **Wednesday, 16-Jan-13 12:55:36 GMT-0500**

It appears that there is an issue with tax calculations as it relates to inclusive taxes and the Shopp donation product.

Calculations appear to come from the price set for a Shopp donation product in the Shopp product editor.

For example: 

If you wanted to accept variable donations, you would set an initial price of 0 and enable variable donations on that product.

Now on the product page, lets say you entered 100 because you want to donate 100. Upon proceeding to the cart, no taxes will be applied.

However if the Shopp donation product has a initial price of 100 in the Shopp product editor, then the taxes are calculated on 100.

Shopp should calculate taxes based on the price in the cart.

###### Steps to Repeat ######

1. Create Shopp donation product with variable pricing and set price to 0
2. Enable inclusive taxes
3. Add to cart and note no taxes are charged on the donation product

###### Relevant Code ######
@@@ php
shopp();
@@@

##### Environment ######
Web Browser: **IE7/IE8/FF3/Safari5/Opera10**
Server OS: **Linux/Windows**
Web Server: **Apache/Nginx**
PHP version: **5.0.1**
WordPress Version: **3.5**
Shopp Version: **1.2.5**
Shopp Install: **fresh/upgrade from 1.2.5**

**Comment by jonathandavis** [comment]
This is no longer relevant with the new inclusive tax model in 1.3
