### ISSUE TITLE
Possible solution for conflict with Slideshow plugin and Shopp

### ISSUE THREAD

**Issue by shopp-lighthouse-import** [ingenesis/shopp#2136]
*Imported from Lighthouse* http://shopp.lighthouseapp.com/projects/47561/tickets/2136
Reported by **Lorenzo Caum** at **Saturday, 19-Jan-13 14:53:34 GMT-0500**

When Shopp & Slideshow plugin (Tribulant) are activated -- then multiple instances of the Colorbox may be loaded.

This causes strange behavior such as the Colorbox not loading or loading with broken functionality.

Workaround: disable one instance of the Colorbox to prevent conflict.

Does Shopp load the colorbox through wp_enqueue_script and wp_enqueue_style functions?

Reference: https://shopplugin.net/support/topic/shopp-plugin-conflicting-with-another-pluginrevisited

**Comment by jonathandavis** [comment]
https://shopplugin.net/kb/broken-image-zoom-slideshow-plugin-tribulant/
