### ISSUE TITLE
API: update customer & customer info

### ISSUE THREAD

**Issue by shopp-lighthouse-import** [ingenesis/shopp#2166]
*Imported from Lighthouse* http://shopp.lighthouseapp.com/projects/47561/tickets/2166
Reported by **Hiranthi** at **Friday, 15-Feb-13 03:42:08 GMT-0500**

We do have add/remove api functions for customers, but not for updating them (entire customer object or specific customer data).

**Comment by jonathandavis** [comment]
We do have developer API for this today with `shopp_set_customer`.

Note that this now needs documentation: https://shopplugin.net/api/shopp_set_customer/

**Comment by Just-m** [comment]
https://shopplugin.net/api/shopp_set_customer/
