### ISSUE TITLE
shopp_recover_password_message example faulty in documentation

### ISSUE THREAD

**Issue by ben72** [ingenesis/shopp#2253]
https://shopplugin.net/api/shopp_recover_password_message/

add_filter('shopp_recover_password_message', 'shopp_recover_password_message_fltr');

// create filter function
<function shopp_recover_password_message( $message ) {
>function shopp_recover_password_message_fltr'( $message ) {

**Comment by jonathandavis** [comment]
Fixed by @lorenzocaum
