### ISSUE TITLE
is_page() returns true for all input on Shopp virtual pages

### ISSUE THREAD

**Issue by clifgriffin** [ingenesis/shopp#2332]
Because Shopp's virtual pages use ID 0 in the query object,  `is_page()` will always return true.

This is due to this quirk:
```php
$test = array('salami');

if ( in_array(0, $test) ) { // this will always run }
```

Filed a trac report here, as this ultimately is a weakness in `is_page()`: http://core.trac.wordpress.org/ticket/24674

**Comment by meredevelopment** [comment]
Is this still an issue since your ticket led to a [core fix](https://core.trac.wordpress.org/changeset/31458) (congrats ;) ?

**Comment by clifgriffin** [comment]
Nope, it's good now :) 

I'll close.
