### ISSUE TITLE
Cart item promotion affecting price on product pages

### ISSUE THREAD

**Issue by ben72** [ingenesis/shopp#2365]
When this promotion is active the price on the product page is 3,08, normal price is 3,50. So it's using the promotion on the product page even though the criteria aren't met. And it shouldn't affect the price displayed on the product page.

Percentage Off - 12%
Apply discount to **cart item** unit price, where:
Name Contains **plint**
When **all** of these conditions match the cart
**Total quantity** **Is greater than or equal to** **10**

http://awesomescreenshot.com/09f1jvga55

Shopp 1.2.8

Ticket #39399 for promotion "Zomeraanbieding plinten".

**Comment by crunnells** [comment]
@ben72 Can you confirm this bug still exists?

**Comment by jonathandavis** [comment]
Reporter has not confirmed. Closing issue. Will reopen if this still occurs.
