### ISSUE TITLE
Shipping updates to NaN with multiple shipping options

### ISSUE THREAD

**Issue by sigmacitizen** [ingenesis/shopp#2385]
On my site there are multiple free shipping options for local areas, if you click through the radio buttons it will randomly assign the shipping cost to "$NaN" the odd time. This has no effect on the final cost and is only visual but annoying. If you need anymore information let me know.

http://gyazo.com/96e512310fa7e6e7e6e67836b1310422.png

Shopp Version 1.2.5

**Comment by jonathandavis** [comment]
No further reports. Reporter has not returned to update it. Closing issue. Will re-open issue if it still exists.
