### ISSUE TITLE
Percentage shipping rates not applied correctly

### ISSUE THREAD

**Issue by ben72** [ingenesis/shopp#2396]
1. Install Shopp 1.2.9 on a clean WP install
2. Set target markets to all countries
3. Enable shipping
4. Add a product at $10
5. Goto rates and enable "Percentage Rate Tiers"
6. Add a destination Europe with 25% shipping rate
7. Add a destination Anywhere with 26% shipping rate
8. Add the product to the cart
9. Select France as destination
Notice how the shipping fee is not $2.5 as expected but $2.6!
If you remove the Europe shipping rate and enter it again so it's last in the list and check in the cart again. Now the shipping is $2.5 as expected!

**Comment by clifgriffin** [comment]
Re-tested with current master. Could not reproduce.
