### ISSUE TITLE
Free shipping promotion not displayed on order

### ISSUE THREAD

**Issue by ben72** [ingenesis/shopp#2475]
The promotions usually displays on the order in the backend. But not if only a free shipping promo is utilized. This is not consistent behavior.
Tested on shopp 1.2.5, 1.2.9 and latest 1.2.x from 7th of October.

One free shipping promo and another promo used (looks ok):
http://awesomescreenshot.com/0791tbk18c

Only free shipping promo used (no trace of the promo!):
http://awesomescreenshot.com/02a1tbhg5d

Also, the discount amount does not take shipping discounts into consideration. This might be by design though?

**Comment by jonathandavis** [comment]
Looks like this issue became invalid with the new 1.3.x approach and fixed in #2583.
