### ISSUE TITLE
Disabled addon options still appear on the product page

### ISSUE THREAD

**Issue by lorenzocaum** [ingenesis/shopp#2481]
WP 3.6.1 , Shopp 1.2.9; also tested on 1.2.x

Create a product and add some add-ons.

View the product's page and ensure that all options are appearing.

Now go back and edit that product to disable one of the options for an addon. For example, if its a shipped product option, change it to disabled. Then save changes: http://cl.ly/image/39371e3X1Y0b

Go back to the products page and note that the disabled option is still appearing: http://cl.ly/image/102C382D402s

**Can anyone confirm?**

**Comment by clifgriffin** [comment]
Tested on current master / WP 4.4 and this no longer occurs.  Closing.
