### ISSUE TITLE
Purchase Addon Label API Issue

### ISSUE THREAD

**Issue by umarglobal** [ingenesis/shopp#2591]
Hi,

When using the following API's both render the same results
<?php shopp('purchase','get-item-addon','label=on'); ?>
<?php shopp('purchase','get-item-addon','name=on'); ?>

This above should output "Artwork : Supplying Own". However It outputs "Supplying Own: Supplying Own".

This is a bug in the template API which needs to be fixed. A patch for this would be appreciated
-----------------------
Wordpress 3.7.1
Shopp 1.2.9

**Comment by umarglobal** [comment]
This bug has not been fixed. Plaese see following ticket: 
https://shopplugin.net/support/topic/receipt-addon-label-issue#post-246457

Wordpress 4.1 , Shopp 1.3.8. Is this most likely going to be fixed at all???

Umar

**Comment by sierrab123** [comment]
From Client, I have not had time to test on a localhost

I have tested this and althought it label=on outputs something it outputes the name of the addon not the label. According to my understanding this is how it should work

Say I have a addon in a particular group called Colour. And the addons in that group is White, Yellow Pink. The addon label=on would output Colour. and the addon name=on would output White or Yellow or Pink depending on the colour selected by the customer. Currently what happens that both the label and name output the White or Yellow or Pink

If my understanding is correct then the bug still presists

**Comment by jonathandavis** [comment]
This was tied to #3175 and the options were updated to sync with the behaviors from `cartitem.item-addons-list`.

The product add-on `label` is the label of the addon (The value given to the add-on itself). The `menu` option will give you the `menu` name (as in `menu=on`).

**Comment by umarglobal** [comment]
This is still not working despite updating the second file provided by steve 
https://github.com/ingenesis/shopp/commit/8f2abc2be3e0bae7c3fc2772f4a3cadca956ee72

Further I have checked the error log and this noticed this fatal error
[09-Mar-2015 19:38:58 UTC] PHP Fatal error:  Call to undefined method ShoppProductThemeAPI::_addon_menus() in /home/cheapasprints/public_html/wp-content/plugins/shopp/api/theme/purchase.php on line 1654

**Comment by umarglobal** [comment]
I have reverted back to 1.3.8 version as fatal errors are causing more issue in the ordering process

Umar
