### ISSUE TITLE
Add back substitutions in shopp_email

### ISSUE THREAD

**Issue by clifgriffin** [ingenesis/shopp#2632]
In backporting e-mail overhauls from 1.3, we accidentally killed $data array subsitutions in `shopp_email`.

**Comment by jonathandavis** [comment]
No longer valid. This was filed against 1.2.x because the data substitutions code was clobbered when 1.3.x email code was back ported in a811091afc079ce7ad06f924366c98df8e632482.

This does not affect 1.3.x forward, and 1.2.x is EOL.
