### ISSUE TITLE
1.2.9 - Product Description Sent to PayPal Standard has +'s instead of spaces

### ISSUE THREAD

**Issue by AnotherTurn** [ingenesis/shopp#2738]
After a destroyed holiday season, thanks to Bluehost, I finally got my first order through my Shopp website using version 1.2.9 (after an upgrade from 1.1.9.1)! But, in PayPal Standard, the product's name was filled with plus signs (+) where the spaces should have been.

![image](https://f.cloud.github.com/assets/2073750/1888049/c3253ce2-7a07-11e3-8eb6-4caf7a78d24f.png)

I should note that the product name itself has a "+" in it, thus the 3 +'s in a row there.

Also, I've upgraded to WP 3.8 since my last issue report.

**Comment by jonathandavis** [comment]
I don't think this is still an issue. Leaving this in Orion Alpha so we can do a quick review.

**Comment by crunnells** [comment]
I can verify that this is *not* an issue in Shopp 1.3.x. I have a couple of clients that only use PPS and have not had a report of this issue.

**Comment by clifgriffin** [comment]
I had a client complain about this with PayFlow Pro I think? Need to check.

**Comment by clifgriffin** [comment]
Confirmed. My issue was Payflow Pro. I agree. Let's close this as I have never seen this happen with PayPal Standard.
