### ISSUE TITLE
Drag and drop reorder of target markets

### ISSUE THREAD

**Issue by msigley** [ingenesis/shopp#2878]
This is a feature request. The order of the target markets as they are saved in the database currently is the order in which they are selected and saved. Since a common checkout optimization is to put certain target markets at the top of the countries drop down, it would be nice if they could be reordered in a drag and drop manner like variations.

At the moment the workaround I implement is to save multiple times forcing the order of the countries a certain way.

**Comment by jonathandavis** [comment]
I have a branch in progress. I submitted a PR earlier (#3460) but it needs some re-sort buttons to reset things if it gets into a mess.

**Comment by jonathandavis** [comment]
This issue will incorporate #3459.

**Comment by crunnells** [comment]
Does that include shipping options and payment methods, or should I submit a new issue specifically for those?

**Comment by jonathandavis** [comment]
This is fully closed with the "Sort Alphabetically" and "Sort by Regions" buttons.
