### ISSUE TITLE
Copy original slug when duplicating product

### ISSUE THREAD

**Issue by ben72** [ingenesis/shopp#2947]
When duplicating a product it would make more sense to copy the slug and add a number at the end. Care has probably been taken to make the slug useful for the original product. This information is wasted when duplicating as the new product forms the slug from the title which is not very useful. This always leads to an extra step for me where I look at the slug for the original product and make the modification needed for the new product.

This is an improvement suggestion.

**Comment by jonathandavis** [comment]
I reviewed this and found we are following WP's behavior exactly. I find no strong case to change it.
