### ISSUE TITLE
1.3.4 Reports. Missing fields and a corrupt file export

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#2979]
I have just had a report of missing fields and a corrupt file on export in the Shopp reports. (products) I have tested this on a localhost and can verify that the file is corrupt although I was able to open the file, the currency field contained a mix of symbols and numbers.

The client says that there are a lot less fields available for sorting compared to the earlier version

A full report of the client's issues can be found https://shopplugin.net/support/topic/report-sorting-options?replies=4#post-234485

**Comment by clifgriffin** [comment]
@jonathandavis Do we need Excel support here over standard CSV? I would vote dropping Excel since Excel and Google Docs both support CSV well.

**Comment by clifgriffin** [comment]
Fixed in 1a66f2597eafdea0e0ae37d9e37df92074572ef5
