### ISSUE TITLE
Product inventory not decreasing for virtual products

### ISSUE THREAD

**Issue by XandaLtd** [ingenesis/shopp#3140]
It works for shipped products, but for virtual ones, the stock isn't being set to decrease at any point despite the relevant inventory settings being set.

The box for Inventory is checked, with an SKU code and stock level entered.  And the setting in System to Enable Inventory Tracking is active, yet it never seems to decrease regardless of how many products get bought.  No messages appear in the logs either...

Any ideas why this is happening?

**Comment by sierrab123** [comment]
Links to https://github.com/ingenesis/shopp/issues/2950 which is closed

**Comment by borkweb** [comment]
I have _only_ been able to reproduce this when using OfflinePayments, and it _appears_ to be related to [this line](https://github.com/ingenesis/shopp/blob/master/core/model/Product.php#L305) where records are being fetched based on the `txnstatus` of `authorized` rather than `authed`.

That being said, I am new enough to Shopp that I _don't_ know if `authorized` _is_ a valid value for that table. What I do know is that OfflinePayments exist in that table as `authed` when they are _Complete_, so [the offending line](https://github.com/ingenesis/shopp/blob/master/core/model/Product.php#L305) fails to fetch the data, which causes the amount sold to appear incorrectly.

**Comment by Just-m** [comment]
Looking at my database I don't think you should change that code.

Offlinepayments need to be charged manually, there is no signal to trigger that payment has succeeded other than a confirmation from the merchant. When this has not happened, the payment status of this order seems to be 'authed'. I don't think these purchases should be included in 'sold'. People can still decide not to send you money, so it is not a completed purchase.

Once manually charged, the status changes to 'captured'. After that these purchases are included in 'sold'.

**Comment by borkweb** [comment]
@Just-m, ah I see what you mean. Marking the Order as "Complete" does not _capture_ the order (as you alluded to in your reply) - instead, I would have to click _into_ the order and click the __"Charge Order"__ button. Once I do that, the database state for that purchase record was updated as you indicated.

All that being said (and forgive my ignorance), it still feels like there is a bug here. I am unclear what the `'authorized'` value in [this query](https://github.com/ingenesis/shopp/blob/master/core/model/Product.php#L305) is for. When I search the codebase for `authorized`, I find no location that `txnstatus` receives _that_ value. What I did find were a number of locations that `authed` was paired with `captured` when looking at the purchase table.

The Shopp help text around Authorized Payments [reads](https://github.com/ingenesis/shopp/blob/master/core/ui/help/management.php#L29):

> When a payment submitted by the customer is authorized by the credit card processor.

Once a record in the purchase table receives the `authed` value, the order is factored into sales reports [here](https://github.com/ingenesis/shopp/blob/master/core/flow/Dashboard.php#L132) and [here](https://github.com/ingenesis/shopp/blob/master/core/flow/Service.php#L220).  I may be wrong, but it seems like reducing the inventory while an order is `authed` would be a desired behavior if `authed` orders _also_ factor into sales.  When `authorized` is changed to `authed` in the [query in question](https://github.com/ingenesis/shopp/blob/master/core/model/Product.php#L305), the behavior appears to work pretty intuitively.  That's a long way to ask: is `authorized` a typo?
