### ISSUE TITLE
Occasional fatal error in Sessions.php

### ISSUE THREAD

**Issue by clifgriffin** [ingenesis/shopp#3164]
I've seen this a few times, but have no idea what condition precipitates it. 

The last time, it happened during a checkout submit:
`PHP Fatal error:  Call to undefined function current_time() in /nas/wp/www/cluster-2706/hollylane/wp-content/plugins/shopp/core/library/Session.php on line 211`

No idea how Sessions.php could possibly be loaded at a time current_time() is not loaded, unless an existing session object is being woken up at the wrong time.  But still...how could that happen before wp-includes/functions.php is loaded?

**Comment by jonathandavis** [comment]
Not heard anything more on this in a long time. Closing for now. Re-open or open a new issue if it re-occurs.
