### ISSUE TITLE
Shopp randomly failing to receive IPNs that have been sent by PayPal

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3177]
As discussed, this is a random issue on some sites. It looks from the PayPal logs that the IPN has been sent, a notification of payment is sent to both merchant and customer, but Shopp is none the wiser and the order remains in an invoiced state

**Comment by sierrab123** [comment]
I have had another similar issue on the HD with the added complication of orders being listed "out of order"

**Comment by sierrab123** [comment]
Just had some more info on this https://shopplugin.net/support/topic/paypal-standard-plugin-producing-duplicate-invoices-intermittent.
Rather than copy and paste the log here it looks as if Shopp is producing 2 orders with one submit

**Comment by sierrab123** [comment]
This may well be tied in with https://github.com/ingenesis/shopp/issues/3233 which is now closed

**Comment by jonathandavis** [comment]
It is **highly** probable that this is related. I noted our IPNs for shopplugin.com are working now.

**Comment by jonathandavis** [comment]
This is resolved by #3233.
