### ISSUE TITLE
Bad redirect after customer changes their password.

### ISSUE THREAD

**Issue by msigley** [ingenesis/shopp#3188]
After the customer changes their password on the account profile page, they are logged out, but redirected to the account profile page again. They should be redirected back to the login page with a message that says something to the affect of "Your password has been updated. Please re-login to you account below."

**Comment by meredevelopment** [comment]
A bit more on this: (1.3.8, WP4.1, Firefox & Chrome)

- After the change and profile page is shown again **The Password hash (from the DB) is shown in the 'New Password' field**, starred out, but visible as the value in source.
- The user has been logged out in the background, any further change attempts get sent to a login screen.
