### ISSUE TITLE
New EU tax laws

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3189]
In a leap of optimism could Shopp taxes be expanded to introduce a tax rate based on category, for EU VAT that now diffs between downloads and services on the one hand and shipped products on the other. IN other words, you could set one EU rate for shipped and a by country rate for downloads and services

**Comment by jonathandavis** [comment]
This is already possible in Shopp 1.3 by including tax rules for tax rates to apply based on product names, tags, or categories. When setting up a tax rate, click the "+" button beside the tax locale to add conditional rules.
