### ISSUE TITLE
Response from Charges API not being read (Pin Payments add-on)

### ISSUE THREAD

**Issue by chrisdahl-pin** [ingenesis/shopp#3194]
We've had multiple Pin Payments customers (who are using Shopp) report transactions that are being displayed as unsuccessful in Shopp whilst the funds have been captured via their Pin Payments account.

There might be a requirement to increase the timeout setting on this add-on. We suggest that it's set to 90 seconds to account for long-running requests (see https://pin.net.au/docs/api).

**Comment by sierrab123** [comment]
You can change this by adding a line to wp-config along these lines


define(SHOPP_GATEWAY_TIMEOUT, 90); 

I would experiment with these settings until you get exactly what you want
