### ISSUE TITLE
Last name not propagating to Billing/Shipping name

### ISSUE THREAD

**Issue by ben72** [ingenesis/shopp#3195]
Using Shopp 1.3.8.
Does not seem to happen on all sites. I reproduced this on a test site though and this is in the helpdesk. No js errors in the console.
First name does propagate.

**Comment by ben72** [comment]
This works again after removed filter function as suggested by @Just-m from line 58-59:
```
.filter(function() {
            return ( this.value === '' );
        })
```
It was introduced here:
https://github.com/ingenesis/shopp/commit/015f455e0213cc5e3ca531cb1bfdf4e797daeb60

**Comment by sierrab123** [comment]
I can confirm that this is happening on a second customer site and also on my test site. Applying the fix suggested by Just Me  and posted by Ben https://gist.github.com/ben72/829301ca29cf14ad6cb4 does indeed remedy the issue on my test site...I am waiting on customer feedback

In addition, at Ben's suggestion I deleted the minified js file in the same core/ui/behaviours folder
