### ISSUE TITLE
Add Media Button for TinyMCE Editor

### ISSUE THREAD

**Issue by jacksonwp** [ingenesis/shopp#3216]
Is there a reason the Add Media button is not available on product and category edit screens? Would be very helpful.

**Comment by jonathandavis** [comment]
They can be enabled by setting the `SHOPP_EDITOR_MEDIA_BTNS` macro.

```
define('SHOPP_EDITOR_MEDIA_BTNS', true);
```

They are off by default to avoid confusion with Shopp product images.

We are looking to transition Shopp back to WP managed media in the future.

**Comment by jacksonwp** [comment]
Thanks, why isn't this documented? Could have saved me hours of work editing client's products for them because they wanted inline images.

**Comment by jonathandavis** [comment]
Not sure, it looks like it just got lost. It's been there since 1.2 I believe.

**Comment by jacksonwp** [comment]
What a shame, lots of folks have been looking for this in the forum.

**Comment by jonathandavis** [comment]
I'll make sure it gets added to the docs pronto.

**Comment by jacksonwp** [comment]
Confusion can be avoided with a warning on the edit product page, eg:

`add_action( 'media_buttons_context',  'shopp_image_warning' );

function shopp_image_warning( $context ) {
    
  if( $_REQUEST['page'] == 'shopp-products' )
      $context.= "<a href='#product-images' class='button'>Add Product Images Below</a>";

  return $context;
}`

**Comment by jacksonwp** [comment]
And an enthusiastic +1 for moving to integration with WP managed media.

**Comment by jonathandavis** [comment]
https://shopplugin.net/api/shopp_editor_media_btns/
