### ISSUE TITLE
Discounts criteria not checked in cart

### ISSUE THREAD

**Issue by ben72** [ingenesis/shopp#3218]
Setup a 20% off discount with the criteria:
"Discounts applied", "is less than", "1"

The discount can be applied with a code in the cart. But on the confirm-order page the discount disappears.

See the discount config here:
https://www.dropbox.com/s/jmdkxczst5juoqz/Selection_144.jpg?dl=0

Tested on Shopp 1.3.8.

This is not critical in itself but confusing.

**Comment by jonathandavis** [comment]
I am not getting this behavior in the latest `1.3.x` branch. Can you verify it still exists as an issue?

**Comment by jonathandavis** [comment]
No new information.

**Comment by jonathandavis** [comment]
No new information. Reopen if the issue still persists on latest `1.3.x`
