### ISSUE TITLE
Featured Product Stars Look Bad in FireFox (possibly others)

### ISSUE THREAD

**Issue by crunnells** [ingenesis/shopp#3219]
Features Product Stars look beautiful in Safari (because it supports `-webkit-background-clip: text;`):
![screenshot 2015-02-06 19 55 38](https://cloud.githubusercontent.com/assets/4297811/6139385/3f73d010-b12f-11e4-811e-4a2eee0b2cbd.png)

Here they are in FireFox (35.0.1):
![screenshot 2015-02-06 19 56 17](https://cloud.githubusercontent.com/assets/4297811/6139393/4ebab05c-b12f-11e4-957f-0ac883d35005.png)

**Comment by jonathandavis** [comment]
These look good in FF now, likely because they are supporting `-webkit-` prefixes now.
