### ISSUE TITLE
Customers receiving wrong receipt!

### ISSUE THREAD

**Issue by dxdc** [ingenesis/shopp#3221]
Recently upgraded to Shopp 1.3.8. Had an issue yesterday where customer #1 paid via Paypal Standard at 4:30pm and customer #2 paid via Stripe at 5:00pm. Customer #2 received the order confirmation email for customer #1! Seems like customer #1 received their correct order email (looking into that still).

Strangely, the admin panel showed correct order information for both orders. Also, the email sent to the Shopp owner (me) was correct for both orders! However, the customer #2 received customer #1's receipt.

I use exclusively guest checkout mode. This is a serious issue! Is there a quick fix that I can apply?

Thanks,
Dan

**Comment by dxdc** [comment]
This is still a pending issue, received a report of it from another customer. I have debug logs enabled so I am happy to submit those as well. I'm not sure if it's a coincidence, but order #103878 was a PayPal order, and #103879 was a Stripe one. The email to the customer for the Stripe order sends the previous PayPal order.




```
2015-03-09 17:10:18 - Shopp: Validating order data for processing [core.php, line 608]
2015-03-09 17:10:18 - PHP NOTICE: Undefined variable: timeout [Order.php, line 277] ShoppErrors->php, ShoppOrder->submit, call_user_func_array, do_action, ShoppCheckout->process, call_user_func_array, do_action, ShoppOrder->request, call_user_func_array, do_action_ref_array, WP->parse_request, WP->main, wp, require [Order.php, line 277]
2015-03-09 17:10:18 - Shopp: PurchaseOrderEvent dispatched. [core.php, line 608]
2015-03-09 17:10:18 - Shopp: Purchase 103879 was successfully saved to the database. [core.php, line 608]
2015-03-09 17:10:18 - Shopp: InvoicedOrderEvent dispatched. [core.php, line 608]
2015-03-09 17:10:18 - Shopp: SaleOrderEvent dispatched. [core.php, line 608]
2015-03-09 17:10:20 - Shopp: AuthedOrderEvent dispatched. [core.php, line 608]
2015-03-09 17:10:20 - Shopp: CapturedOrderEvent dispatched. [core.php, line 608]
2015-03-09 17:10:20 - Shopp: NoticeOrderEvent dispatched. [core.php, line 608]
2015-03-09 17:10:20 - Shopp: ShoppPurchase::email(): John Smith,js@thecustomer.com,Your order with Element TwentySix,Array
(
[0] => email-order.php
[1] => order.php
[2] => order.html
)
[core.php, line 608]
2015-03-09 17:10:20 - PHP Warning: A
, not a
tag must occur inside a
tag. [Email.php, line 853] ShoppErrors->php, trigger_error, TextifyTd->__construct, TextifyTag->renderer, TextifyTable->render, TextifyTag->render, TextifyTag->render, TextifyTag->render, TextifyTable->render, TextifyTag->render, TextifyTag->render, TextifyTag->render, TextifyTable->render, TextifyTag->render, TextifyTag->render, TextifyTag->render, TextifyTable->render, TextifyTag->render, TextifyTag->render, Textify->render, ShoppEmailFilters->AltBody, call_user_func_array, do_action_ref_array, wp_mail, ShoppCore->email, ShoppPurchase->email, ShoppPurchase->success, call_user_func_array, do_action, ShoppOrder->notify, call_user_func_array, do_action_ref_array, OrderEventMessage->__construct, OrderEvent->add, shopp_add_order_event, ShoppOrder->captured, call_user_func_array, do_action_ref_array, OrderEventMessage->__construct, AuthedOrderEvent->__construct, OrderEvent->add, shopp_add_order_event, Stripe->sale, call_user_func_array, do_action_ref_array, OrderEventMessage->__construct, OrderEvent->add, shopp_add_order_event, ShoppOrder->sale, call_user_func, ShoppOrder->process, call_user_func_array, do_action, ShoppOrder->purchase, call_user_func_array, do_action_ref_array, OrderEventMessage->__construct, OrderEvent->add, shopp_add_order_event, ShoppOrder->submit, call_user_func_array, do_action, ShoppCheckout->process, call_user_func_array, do_action, ShoppOrder->request, call_user_func_array, do_action_ref_array, WP->parse_request, WP->main, wp, require [Email.php, line 853]
2015-03-09 17:10:20 - PHP Warning: A
, not a
tag must occur inside a
tag. [Email.php, line 853] ShoppErrors->php, trigger_error, TextifyTd->__construct, TextifyTag->renderer, TextifyTable->render, TextifyTag->render, TextifyTag->render, TextifyTag->render, TextifyTable->render, TextifyTag->render, TextifyTag->render, TextifyTag->render, TextifyTable->render, TextifyTag->render, TextifyTag->render, TextifyTag->render, TextifyTable->render, TextifyTag->render, TextifyTag->render, Textify->render, ShoppEmailFilters->AltBody, call_user_func_array, do_action_ref_array, wp_mail, ShoppCore->email, ShoppPurchase->email, ShoppPurchase->success, call_user_func_array, do_action, ShoppOrder->notify, call_user_func_array, do_action_ref_array, OrderEventMessage->__construct, OrderEvent->add, shopp_add_order_event, ShoppOrder->captured, call_user_func_array, do_action_ref_array, OrderEventMessage->__construct, AuthedOrderEvent->__construct, OrderEvent->add, shopp_add_order_event, Stripe->sale, call_user_func_array, do_action_ref_array, OrderEventMessage->__construct, OrderEvent->add, shopp_add_order_event, ShoppOrder->sale, call_user_func, ShoppOrder->process, call_user_func_array, do_action, ShoppOrder->purchase, call_user_func_array, do_action_ref_array, OrderEventMessage->__construct, OrderEvent->add, shopp_add_order_event, ShoppOrder->submit, call_user_func_array, do_action, ShoppCheckout->process, call_user_func_array, do_action, ShoppOrder->request, call_user_func_array, do_action_ref_array, WP->parse_request, WP->main, wp, require [Email.php, line 853]
2015-03-09 17:10:20 - Shopp: A purchase notification was sent to: "John Smith" [core.php, line 608]
```

**Comment by Just-m** [comment]
Did it happen again after you made the change to the caching plugin settings?

**Comment by dxdc** [comment]
I haven't seen it. I also have a mail tracking plugin now thanks to @chaoix so I'll be able to track it if it comes up again.

**Comment by Just-m** [comment]
Thanks. It is a good thing to keep tickets up to date so people don't start hunting for errors unnecessary.

**Comment by dxdc** [comment]
Sorry, I generally try to.... I haven't seen anything, but I'm still
watching. It's very difficult to track because the only way I can really
track it is by customer complaint (and not all customers would complain).

**Comment by dxdc** [comment]
Turns out this is still ongoing. I'm running 1.3.10 branch.

Customer 1 places order. Receives correct email.
Customer 2 places order (10 min later). Receives correct email, but all of the order information on receipt page is from Customer 1.

It's definitely some sort of caching issue... any ideas on how to resolve this (or if there is some inherent caching functions within WP/Shopp that need to be updated)?

**Comment by dxdc** [comment]
I may have made some progress on this issue, and probably should be included with the Shopp documentation.

While only time will tell, it may have to do with the sendfile directive in my nginx configuration file.

Since I'm running a virtualized server (Xen), it seems sendfile can cause issues serving stale content with both nginx and apache and is trivial to turn off. I'm going to close this issue for now, since everything I've read makes me believe it's the cause, but will reopen if I find anything else about it.

Regardless, it should be turned off for any virtualized server!

https://coderwall.com/p/ztskha/vagrant-apache-nginx-serving-outdated-static-files-turn-off-sendfile
https://www.vanpattenmedia.com/2012/a-tale-of-stale-content
