### ISSUE TITLE
Shopp products not saving with ACF relationship field

### ISSUE THREAD

**Issue by podoglyph** [ingenesis/shopp#3222]
Hi,

This problem arises when I use an ACF relationship field on a Shopp product. If the relationship field is used the product won't save. Could you please read below and verify or offer some insight? I contacted Elliot Condon and he made the following reply:

"I've done some debugging, and believe I have found the issue. Unfortunately, I won't be able to fix it from ACF's end, but if you are able to contact Shopp and get a conversation going, that would be great.

The issue seems to be that some JS (assumed from the Shopp plugin) is preventing the form submit event from being triggered. I have done some testing and can confirm that when editing a product in Shopp, the form submit event is never fired which is very strange. This prevents ACF from running validation, and from unhooking the navigation prompt."

**Comment by Just-m** [comment]
I did some testing with ACF 4.4.2 and Shopp 1.3.9 and had no problem saving a product.

Do you still see this issue in Shopp 1.3.9?
If so could you explain in more detail the setup of the fields?

**Comment by msigley** [comment]
@podoglyph: Are you using a file input field from ACF? IE has a security feature that prevents simulated file inputs and javascript submit handlers from being used on the same form.

**Comment by podoglyph** [comment]
I'm using ACF Pro 5.3.1 and Shopp 1.4dev. I'm using a relationship field with a custom post type in order to save an Artist to a Shopp product. I choose an Artist and then when I click Save Product I get an alert that says "Confirm Navigation - Are you sure you want to leave this page? The changes you made will be lost if you leave this page."

After some further testing it seems I can't save any type of ACF Field on a Shopp product.

I'm not sure where to go now. There aren't any errors I can see.

**Comment by Just-m** [comment]
Can you try with Shopp 1.3.9 version? Version 1.4dev is for testing only, not to be used for live shops yet.

**Comment by crunnells** [comment]
I can confirm that ACF Pro 5.3.1 works with Shopp 1.3.9. Just-M is right, 1.4dev isn't for ready for live sites.

**Comment by podoglyph** [comment]
I wondered about that. Not sure why the dev version was active. With 1.3.9 the problem persists. I changed to a default WP theme, and deactivated all plugins, and created a new ACF to test, but no luck.

**Comment by crunnells** [comment]
It works on my site, despite the alert you describe. If you click "Leave site" it doesn't actually leave the site and it saves the ACF data. I'm not sure what triggers that warning, but it needs fixing.

**Comment by crunnells** [comment]
I just checked the latest version of non-pro ACF (4.4.3) and it does not have this problem, so there's some additional JS loaded in ACF Pro that causes this issue.

**Comment by podoglyph** [comment]
Thanks guys. I send an update to ACF to see if they can confirm whether or not some additional JS in ACF Pro is the cause of this problem. Thanks for your assistance!
