### ISSUE TITLE
Genesis, Permalinks and Shopp won't play together

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3240]
I have narrowed my Permalinks issue to the Genesis theme and virtual pages. There was a previous issue reported in Shopp https://shopplugin.net/kb/shopp-storefront-product-collection-pages-stripped-in-genesis-themes/

Mine is different insofar as when trying to enable Permalinks, the Shopp storefront becomes unavailable from the menu, the only item on the menu to do so

**Comment by crunnells** [comment]
Which Genesis theme are you using? Could be theme specific, as I'm using the vanilla Genesis theme locally and haven't run into any problems with virtual pages.

**Comment by sierrab123** [comment]
After days of testing, I checked out my localhost (almost) clone and found the issue does not exist there, so I have now just contacted the host to see why only the Shopp pages won't play pretty on the live site

**Comment by sierrab123** [comment]
Caused by faulty settings on WP reading page in settings
