### ISSUE TITLE
PayPal Pro Loop Problem

### ISSUE THREAD

**Issue by pensandpencils** [ingenesis/shopp#3245]
Hi, 

Seem to be having a problem with PayPal Pro 1.2.9 with Shopp 1.2.8. SSL certificate is in place and valid.

Products in cart.
On checkout page - card details added, click to confirm order.
Taken to Confirm Order page, click to finalise payment.
Then returned to checkout page - CC numbers x'd out except last 4 digits and Security Code removed.
Try to add details and then taken to Confirm Order page, click to finalise payment.
Then returned to checkout page and so on and so forth.

Any thoughts what might be happening - help would be greatly appreciated.

Thanks

**Comment by crunnells** [comment]
This problem is likely related to #3203 which has been fixed and is slated for the next release of Shopp (1.3.9).

**Comment by pensandpencils** [comment]
Can confirm that it isn't  - have tried both of those solutions and they haven't worked. Have used that fix before to sort out Paypal Standard payment not working, so had already tried it - should have mentioned.

Additionally Paypal Standard is working absolutely fine. Issue is with the premium Paypal Pro plugin.

Thanks crunnells for the swift response btw.

**Comment by crunnells** [comment]
Do you have debugging logging turned on? Anything relevant to the order showing up in there?

**Comment by pensandpencils** [comment]
Have got that set up now - klutz-like I overlooked having that running...

Incidentally orders now working on Paypal Pro, same details/browsers used and suddenly orders coming through fine, so appears to a infrequent issue. Curious.

**Comment by pensandpencils** [comment]
Here is an error that maybe related as its happening to someone going through the above(file path x'd out):

`2015-03-06 11:48:40 - PHP WARNING: is_readable(): open_basedir restriction in effect. File(/dev/urandom) is not within the allowed path(s): (/xxx/xxx/xxxx/xxxxxxxxxxx/:/tmp/) ShoppErrors->php, is_readable, ShoppSessionFramework->entropy, ShoppSessionFramework->session, ShoppSessionFramework->cook, ShoppSessionFramework->__construct, Shopping->__construct, Shopping->object, Shopping->restore, ShoppErrorStorefrontNotices->init, call_user_func_array, do_action, require_once, require_once, require_once, require [Session.php, line 451]`

Followed by:

`2015-03-06 11:50:57 - PHP NOTICE: Undefined variable: timeout ShoppErrors->php, ShoppOrder->submit, call_user_func_array, do_action, ShoppCheckout->confirmed, call_user_func_array, do_action, ShoppOrder->request, call_user_func_array, do_action_ref_array, WP->parse_request, WP->main, wp, require [Order.php, line 276]`

Don't know if that may shed any light...

**Comment by jonathandavis** [comment]
`open_basedir` restriction error is strange. The `ShoppSessionFramework->entropy()` call shouldn't have anything reading from `/tmp/`, and `/dev/` is not listed there either. That is very puzzling. It wouldn't affect anything because there are fallbacks for entropy generation.

The undefined `$timeout` just got fixed, but again, it doesn't actually break checkout, it would break the locking system from working effectively. It means you'd have intermittent duplicate order prevention.

**Comment by msigley** [comment]
The openbase_dir restriction warning is caused by a security restriction in place by the webhost or a security plugin. 
http://php.net/manual/en/ini.core.php#ini.open-basedir
@pensandpencils are you using any security plugins on this site? Shopp uses the unix random number generator in generating session codes, but is built to work fine if /dev/urandom/ is unreadable.
https://github.com/ingenesis/shopp/blob/1.3.x/core/library/Session.php#L451

The issue you are describing with the redirect back to checkout with Paypal sounds like it may be a caching issue. Are you using any caching plugins on the site or are you on a host that does aggressive server side caching like WP Engine?

**Comment by pensandpencils** [comment]
Hi @msigley ,

Not as far as I'm aware - All in One SEO is probably the only one the site owner is using that maybe could cause that kind of caching - that possible do you think?

Thanks for all your help on this guys, glad its not just me a little baffled by it!

**Comment by jonathandavis** [comment]
So the `is_readable('/dev/urandom')` is throwing the error. Should be sufficient to suppress the error in this case.

**Comment by jonathandavis** [comment]
Unfortunately intermittent problems are the worst case scenario to troubleshoot. My only recommendation is to gather as much information about how and when it is happening. Are there times that it happens more often? Any recent configuration changes? Literally as much information as you can possibly dig up is the only thing that might lead to a solution.

**Comment by pensandpencils** [comment]
Currently checking on any recent updates the site owner may have made.

When you say:
>So the is_readable('/dev/urandom') is throwing the error. Should be sufficient to suppress the error in this case.

What do you mean by this? Is there anything I can do to test the above.

As I keep saying thanks so much, really appreciate you all looking into it.

**Comment by pensandpencils** [comment]
Can also confirm that the above loop issue only started happening when the Shopp was updated to the latest version and WP was updated too - previous to the upgrade the security code would auto clear and have to be reentered I've just been informed.

Out of interest when was the last time the Paypal Pro plugin was updated? And what is the lastest version?

**Comment by pensandpencils** [comment]
Have done another test and this further error codes that are logged in addition to the above:

`2015-03-08 15:06:09 - PHP NOTICE: Undefined variable: loading [product.php, line 1098] ShoppErrors->php, ShoppProductThemeAPI->image, call_user_func_array, apply_filters, shopp, require, load_template, ShoppCore->locate_template, locate_shopp_template, ShoppProductPage->content, call_user_func_array, apply_filters, the_content, include, require_once, require [product.php, line 1098]`

`2015-03-08 15:06:12 - Shopp: Session started ---------------------------------------------------------------- [core.php, line 608]`

`2015-03-08 15:06:12 - Shopp: Session started ---------------------------------------------------------------- [core.php, line 608]`

`2015-03-08 15:06:13 - Shopp: Session started ---------------------------------------------------------------- [core.php, line 608]`

`2015-03-08 15:06:16 - Shopp: Session started ---------------------------------------------------------------- [core.php, line 608]`

`2015-03-08 15:06:17 - Shopp: Session started ---------------------------------------------------------------- [core.php, line 608]`

`2015-03-08 15:06:18 - PHP NOTICE: Undefined offset: 0 [Modules.php, line 401] ShoppErrors->php, ModuleFile->baseversion, ModuleFile->valid, ModuleFile->__construct, ModuleLoader->installed, ShoppAPIModules->__construct, Shopp->init, call_user_func_array, do_action, require_once, require_once, require_once [Modules.php, line 401]`

`2015-03-08 15:06:18 - PHP NOTICE: Undefined offset: 0 [Modules.php, line 401] ShoppErrors->php, ModuleFile->baseversion, ModuleFile->valid, ModuleLoader->installed, ShoppAPIModules->__construct, Shopp->init, call_user_func_array, do_action, require_once, require_once, require_once [Modules.php, line 401]`

**Comment by msigley** [comment]
@pensandpencils: Nothing jumps out at me in this latest error log you provided.

What we mean by suppressing the is_readable error is changes to the plugin code to prevent that error from being logged since that particular error is harmless, the session code is designed to work fine in the absence of unix random number generator.

The latest version of Paypal Pro is 1.2.9. I would definitely upgrade to the latest version of the Paypal Pro gateway if you are using the latest version of WP and Shopp.
https://shopplugin.net/store/paypal-pro/

**Comment by pensandpencils** [comment]
@msigley apologies, been out of office a little.

Back to testing on this, just got a new error - will doublecheck with client about Paypal API details (they were correct as of last week) but it might help in some way:

`[PayPalPro.php, line 586]`

`2015-03-18 07:36:49 - PayPalPro: XML Response: Error Processing Lookup Request Message, Invalid Merchant Id or Processor Id, Error Validating Merchant Id Value, Error Validating Processor Id Value1002, 2002, 4020, 40009woxNhntbHH4SdisVHh0U [PayPalPro.php, line 586]`

**Comment by pensandpencils** [comment]
@msigley Further to this here is the log for the actual moment the loop occurs - apologies for all the text but thought it may help - this then leads on to the above error:

`2015-03-18 07:35:54 - Shopp: Session started ---------------------------------------------------------------- [core.php, line 608]`
`2015-03-18 07:35:54 - Shopp: Redirecting to: https://xxxxxx.co.uk/shop/basket/ [core.php, line 608]`
`2015-03-18 07:36:15 - Shopp: Session started ---------------------------------------------------------------- [core.php, line 608]`
`2015-03-18 07:36:15 - Shopp: Redirecting to: https://xxxxxx.co.uk/shop/checkout/ [core.php, line 608]`
`2015-03-18 07:36:45 - Shopp: Session started ---------------------------------------------------------------- [core.php, line 608]`
`2015-03-18 07:36:45 - Shopp: Switching the session to secure mode. [core.php, line 608]`
`2015-03-18 07:36:45 - Shopp: Redirecting to: https://xxxxxx.co.uk/shop/confirm-order/ [core.php, line 608]`
`2015-03-18 07:36:45 - Shopp: Cart saving in secure mode! [core.php, line 608]`
`2015-03-18 07:36:46 - Shopp: Session started ---------------------------------------------------------------- [core.php, line 608]`
`2015-03-18 07:36:46 - Shopp: Validating order data for processing [core.php, line 608]`
`2015-03-18 07:36:49 - Shopp: Session started ---------------------------------------------------------------- [core.php, line 608]`
`2015-03-18 07:36:49 - Shopp: Validating order data for processing [core.php, line 608]`

`2015-03-18 07:36:49 - PHP NOTICE: Undefined variable: timeout [Order.php, line 276] ShoppErrors->php, ShoppOrder->submit, call_user_func_array, do_action, ShoppCheckout->confirmed, call_user_func_array, do_action, ShoppOrder->request, call_user_func_array, do_action_ref_array, WP->parse_request, WP->main, wp, require [Order.php, line 276]`

`2015-03-18 07:36:49 - Shopp: PurchaseOrderEvent dispatched. [core.php, line 608]`
`2015-03-18 07:36:49 - Shopp: Purchase 936 was successfully saved to the database. [core.php, line 608]`
`2015-03-18 07:36:49 - Shopp: InvoicedOrderEvent dispatched. [core.php, line 608]`
`2015-03-18 07:36:49 - Shopp: SaleOrderEvent dispatched. [core.php, line 608]`
`2015-03-18 07:36:49 - PayPalPro: process() tdsecure true`
`2015-03-18 07:36:49 - PayPalPro: process() !enrolled run tds_lookup()`
`2015-03-18 07:36:49 - PayPalPro: XML Request: url(https://paypal.cardinalcommerce.com/maps/txns.asp) cmpi_msg=
1.7`

**Comment by pensandpencils** [comment]
Hi,

Can now confirm that this is happening on two different sites using Paypal Pro - the error:

`2015-03-24 07:17:15 - PayPalPro: XML Response: Error Processing Lookup Request Message, Invalid Merchant Id or Processor Id, Error Validating Merchant Id Value, Error Validating Processor Id Value1002, 2002, 4020, 4000MdRLCjsFZAPBLLRPB5I0U [PayPalPro.php, line 586]`

appears again - on both of these sites 3D Secure is not installed - however its pretty widely documented that 3D secure is not required unless using Maestro cards and nowhere in the Shopp documentation (that I could find) does it say anything about whether its needed or not - or even a suggestion as to how to sign up if so.

My question @jonathandavis @crunnells @msigley - does the Paypal Pro plugin NEED 3d Secure access details to work? Simple question.

Would be great to have some kind of response.

Thanks all.

**Comment by msigley** [comment]
@pensandpencils: 3D Secure is not required by any Payment gateway.

**Comment by pensandpencils** [comment]
Any idea why it might be flagging up an error message relating to it then?

**Comment by msigley** [comment]
I was just informed by @jonathandavis that 3D Secure is required for all UK merchants. Does this affect you? This might be cause by something in your hosting environment. Could you submit a ticket through the Shopp Helpdesk so someone can work with you directly?

**Comment by pensandpencils** [comment]
Hey, @msigley @jonathandavis  - yep UK based - if this fixes it you'll be the first to know.

Had a ticket on the helpdesk at the same time, just been told about the 3D Secure/UK thing just now.

Will report back.
Thanks!

**Comment by jonathandavis** [comment]
@pensandpencils are you enrolled in 3DSecure through Cardinal Commerce?
