### ISSUE TITLE
FedEx insurance not working due to missing index

### ISSUE THREAD

**Issue by adamsewell** [ingenesis/shopp#3247]
On line 203 in the FedExRates file, Shopp uses the value function to get the product amount, however the value function which just returns val from the object. val is calculated in Shipping on line 1886 which the price is pulled from the parentItem which uses the index of the object. The index for whatever reason is not set causing the insurance in FedEx to return 0 for the value of the insured item.

**Comment by adamsewell** [comment]
Need to add a small blurb to the ShippingPackageItem construct function.

```php
		if(is_a($Item, 'ShoppShippableItem')){
			foreach ( shopp_cart_items() as $index => $CartItem ){
				$this->index = $index;
			}
		}
```

**Comment by jonathandavis** [comment]
Moved to private issue tracker.
