### ISSUE TITLE
Retrying Paypal payment just goes back to checkout

### ISSUE THREAD

**Issue by mcary** [ingenesis/shopp#3250]
I think I've found an issue with issue #3142:  With Paypal Standard, if the user clicks the back button after reaching paypal or otherwise tries to pay again before completing the original trip to paypal, they get stuck on the checkout page.  In other words, submitting the checkout page just takes them back to the checkout page again.

I think I have a fix.  Would you entertain a pull request if I prepare one?

**Comment by jonathandavis** [comment]
Absolutely! We're very open to PRs. The wiki has details on the process: https://github.com/ingenesis/shopp/wiki/Submissions

**Comment by mcary** [comment]
Oops, I see it was fixed by commit aab376e73.

**Comment by mcary** [comment]
Looks like the fix is not yet released yet; the latest download is still 1.3.8.  Should I try running master to get the fix on a production system, or is it likely to be unstable?  Else I could just apply that one patch to 1.3.8.

**Comment by jonathandavis** [comment]
Your best bet is to grab the `1.3.x` branch version which is de-facto 1.3.9 at this point. It is stable. At the moment I would not use `master`.

Alternatively you could apply the fix as just a patch to your site, but there are a number of other important fixes in `1.3.x` that would be worth including.

**Comment by jonathandavis** [comment]
In the future, if you find anything else you can submit a PR anytime for fixes or proposed features. Thanks for contributing!
