### ISSUE TITLE
1.3.9 dev is automatically logging errors without intervention

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3251]
Vanilla install wp 4.1.1 and shopp 1.3.9 dev

With error logging disabled (default) Shopp is logging errors. (localhost)

**Comment by jonathandavis** [comment]
@sierrab123 do you have `WP_DEBUG` enabled in `wp-config.php`?

**Comment by sierrab123** [comment]
No, I just checked

**Comment by sierrab123** [comment]
Just created a new enviri (non xampp) the error logging does not happen
