### ISSUE TITLE
Category discount is not applied to new products before the discount is re-enabled

### ISSUE THREAD

**Issue by ben72** [ingenesis/shopp#3255]
1. Add a percentage off catalog discount
Notice the products are now discounted
2. Create a new product
Notice the new product is not discounted!
3. Disable the discount and re-enable it
Notice the new product is now discounted like it should be.

This is the same if you unpublish and re-publish a product. The discount is lost on that product until the discount is disabled and re-enabled.

Tested on Shopp 1.3.8 and 1.3.9dev.

**Comment by lorenzocaum** [comment]
This sounds similar to #3068

**Comment by ben72** [comment]
Yes this can be closed as a duplicate. So either re-enable or re-save the discount makes it apply to a newly created product.
