### ISSUE TITLE
shopp('product','variations','mode=single') doesn't work 

### ISSUE THREAD

**Issue by ben72** [ingenesis/shopp#3265]
When using this line in product.php with the only change that mode=single instead of mode=multiple results in an empty select box:

```<?php shopp( 'product.variants', 'mode=single&label=true&defaults=' . __( 'Select an option', 'Shopp') . '&before_menu=<li>&after_menu=</li>' ); ?>```

Testsed on 1.3.8.

**Comment by ben72** [comment]
And possible the API docs should change from using variations to variants? Both seem to work though.

**Comment by Just-m** [comment]
I tried to replicate the issue but it seems to work fine. What does your product look like?

**Comment by ben72** [comment]
Just had two different variant selectors Size and Color with a few variants in each. Tested on a vanilla 1.3.8.

**Comment by Just-m** [comment]
weird I used the same setup. Shipped product? or other type?

**Comment by Just-m** [comment]
Sorry, I was testing it the wrong way. I don't get the same result as you do, but I do get a wrong result. I'll test some more.
