### ISSUE TITLE
VAT exclusive prices and variations

### ISSUE THREAD

**Issue by clifgriffin** [ingenesis/shopp#3267]
First of all, my client is really happy that Shopp now removes VAT from prices when selecting a non-EU country. :+1: 

I noticed a couple of glitches with it in practice, relating to variations.

Scenario:
- Base country Germany
- Tax settings: EU 20%
- Product with Variations:  Variation A: 1,000 Variation B: 2,000

Steps to Reproduce:
1) Add product to cart, selecting variation A
2) In cart, switch target country to USA. Price drops to 833.33 as expected.
3) Going back to product page, price is now listed as 833.33 - 1667.77 as expected
4) However: variation dropdown still lists VAT inclusive prices for both options
5) In cart, variant menu on cart item shows VAT inclusive adjustment amounts. 
6) Worse, selecting a new variant and pressing update saves the selection, but the prices stay the same (cart item and totals)

~~I actually think 6 might be a bug by itself, unrelated to taxes.  I can open as a separate issue if preferred.~~ UPDATE: It is VAT related. If using an EU jurisdiction, prices update on new options selection as expected.

**Comment by sierrab123** [comment]
Can confirm the above with 1.3.9 dev

1 item 2 variations, black and white €1,000 and €2,000

With France as customer country cart updates when swsitching between black and while as it should

Switching to USA there is no updating when you switch from black to white also the dropdown description is strange showing white as +1166.67
