### ISSUE TITLE
Add php-xml to requirements checking

### ISSUE THREAD

**Issue by jonathandavis** [ingenesis/shopp#3269]
An install of Shopp reported a fatal error while trying to send notes to customers:

> PHP Fatal error: Class 'DOMDocument' not found

The current requirements check does not appear to catch this.

**Comment by clifgriffin** [comment]
@jonathandavis This is available in PHP 5 and 7, all versions as far as the documents reveal. I don't see how it's possible for someone to not have this?

**Comment by clifgriffin** [comment]
Hmm, it looks like it's possible to install PHP without this library: https://wordpress.org/support/topic/plugin-import-html-pages-requires-php-xml-if-you-get-error-domdocument-not-found?replies=1

Wondering if we should just gracefully degrade.

**Comment by jonathandavis** [comment]
`DOMDocument` is required for Textify. I'd say if it does exist, we should not enable Textify, meaning you only get one format for your emails.

**Comment by clifgriffin** [comment]
@jonathandavis Do we need more than this? 

```php
	static function AltBody ( $phpmailer ) {
		// If DOMDocument, don't implement Textify (no alternate plaintext body will be sent)
		if ( ! class_exists('DOMDocument') ) return;

		$Textify = new Textify($phpmailer->Body);
		$phpmailer->AltBody = $Textify->render();
	}

```

**Comment by clifgriffin** [comment]
(I fixed the typo in the comment)
