### ISSUE TITLE
EU/USA cart and VAT with variables 1.3.9 dev

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3272]
1 item 2 variations, black and white €1,000 and €2,000

With France as customer country cart updates when switching between black and while as it should

Switching to USA there is no updating when you switch from black to white also the drop down description is strange showing white as +1166.67 which is the gross difference plus the missing VAT from the current selected variation

**Comment by sierrab123** [comment]
Just confirmed this is still an issue in 1.3.10

**Comment by clifgriffin** [comment]
Hmm, I have never seen this happen.  I will test again.

**Comment by Just-m** [comment]
Fixed  by #3673
