### ISSUE TITLE
Shopp icons missing on live site

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3273]
On live site 1.3.9 shop icons do not exist in admin after upgrade to 1.3.9
On localhost identical copy of the same site icons exist after upgrade

**Comment by ben72** [comment]
I got the same issues when I used /wp-content/plugins/shopp-1.3.x as plugin directory. It was resolved when I renamed it to shopp.

**Comment by sierrab123** [comment]
I see, I updated from WordPress and it is downloading as shopp.git

Once I renamed to shopp the icons reappeared

**Comment by sierrab123** [comment]
Just tried again and it downloaded as normal no sign of .git

**Comment by jacksonwp** [comment]
I just experienced this upgrading a live site via the plugins page. The main symptom for me was that the listing of Products in the admin was blank, and the edit product links from the front-end didn't work. Renaming the folder and reactivating the plugin solves the problem.

**Comment by ben72** [comment]
@jacksonwp yes, currently the directory needs to be named "shopp". This might need to get fixed @jonathandavis?

**Comment by jacksonwp** [comment]
I get that, and it was named shopp before I upgraded. The upgrade routine produced the shopp.git directory.

**Comment by ben72** [comment]
Yes I just saw that reported. @jonathandavis is looking into that.
