### ISSUE TITLE
1.3.9 Released - Product Admin Page shows no products

### ISSUE THREAD

**Issue by pensandpencils** [ingenesis/shopp#3275]
1.3.9 is showing as available in Plugin updates - client updated and now no products showing in the backend of the site at the new Products url:

wp-admin/admin.php?page=shoppgit-products

Also a lesser issue but custom icons not visible in the sidebar of admin:

![screenshot 2015-03-31 10 43 23](https://cloud.githubusercontent.com/assets/386365/6916279/e6bd248c-d792-11e4-85c2-dfd975772864.png)

**Comment by ben72** [comment]
Disable Shopp, rename the directory shopp and re-enable it.

**Comment by ben72** [comment]
Related to #3273.

**Comment by pensandpencils** [comment]
Thanks Ben,

Had the same .git issue.

Missed that!

M
