### ISSUE TITLE
Mark Orders as Completed

### ISSUE THREAD

**Issue by jacksonwp** [ingenesis/shopp#3285]
Is there a reason you cannot mark an order as completed without going batch to the Orders list? Would be really helpful to change order status from the order detail view.

**Comment by sierrab123** [comment]
Could this be added to the feature admin orders feature or is it already in that branch?

**Comment by ben72** [comment]
@crunnells has some plugin/fix which fixes this. It would be great to have in the core though.

**Comment by Just-m** [comment]
There must be a good reason because the "in-order-status-update" is how it used to work way back. It changed somewhere along the path from 1.1 to 1.3.

**Comment by jacksonwp** [comment]
Having just filled 24 shipped orders in a day personally, I can say it's really an inefficient back-end for fulfillment and processing shipped orders.

**Comment by crunnells** [comment]
Here's a link to my plugin: http://www.chrisrunnells.com/wp-content/uploads/2015/04/shopp-admin-extras.zip

It adds a meta box to the orders page that lets you change the order status, and also adds links to the top of the orders page that directs to next and previous pending orders. I'm submitting it to the WP plugins directory as well, but that may take a few days.

**Comment by jacksonwp** [comment]
@crunnells this is excellent, thanks very much. +1 on including these features in core

**Comment by crunnells** [comment]
It's also available on the WP plugins directory now: https://wordpress.org/plugins/shopp-admin-extras/

**Comment by jacksonwp** [comment]
Thanks for this Chris, just filed my first bug report for this plugin at WP.org.

**Comment by crunnells** [comment]
Hah! Thanks. I wonder if it's been broken on my client's site and they never told me. I'll check into it today.
