### ISSUE TITLE
Extra shipping charges are added on top of "original" shipping charge in cart

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3290]
If you handle all shipping charges through extra shipping costs and you have variations, when changing the variations in the cart the new variation's charges are added on top of the original charges rather than substituting for them

**Comment by jjonesslamdot** [comment]
Following this issue.

**Comment by sierrab123** [comment]
So to make this clearer, A site has no shipping charges enabled, just  a flat shipping fee of zero dollars.

Actual shipping charges are added to the order by the use of extra shipping fees on each variation. For example a bed will have 2 variations, single and double. The single bed will have an extra fee of $30 and the double will have an extra fee of $50.

So if you have ordered a single bed and all of a sudden become romantically involved or just fatter before reaching the cart page and wish to change your order to a double bed on the cart page, the shipping will become $80 rather than $50.

It is adding the new rate on top of the old one rather than substituting it. I have confirmed this on a test site

**Comment by msigley** [comment]
Ok. I found and hunted down the code that is causing this:
https://github.com/ingenesis/shopp/blob/1.3.x/core/model/Cart.php#L503

The change item algorithm handles adding new shipping charges to the cart, but not removing existing ones. I'll start working on a patch to fix this.

**Comment by sierrab123** [comment]
https://github.com/ingenesis/shopp/pull/3541

**Comment by Just-m** [comment]
Fixed by commit https://github.com/ingenesis/shopp/commit/15416479283bac507274bdd53debcfca22031b47#diff-c747d5eda5638851e5b03e7f6f5366ee
