### ISSUE TITLE
PayPal Standard 'address_override' option

### ISSUE THREAD

**Issue by crunnells** [ingenesis/shopp#3293]
The 'address_override' setting in the base PayPal Standard module can cause errors for customers in certain situations. I think it would be good if we added an option to the payment module that allows the merchant to turn the override on or off. Currently the only option is to change the module, which will be overwritten the next time Shopp updates.

**Comment by jonathandavis** [comment]
Can you elaborate on "certain situations"?

**Comment by crunnells** [comment]
I can't remember now. There was a situation I had with a client in the Netherlands that ships their product all over the world, and they were running into some issue with PayPal addresses. In hindsight, I think it's possible that the errors were related to just bad addresses--instead of the address override option--since it seems like this is the functionality we want. I guess if address_override was set to 0, PayPal might not complain about bad address data being sent from Shopp (as entered by the customer). I'm closing this until I can remember why I opened it in the first place.

**Comment by crunnells** [comment]
This issue cropped up again. For whatever reason, my customer has a lot of trouble with out-of-country addresses not matching PayPal's verification system... I haven't done an exhaustive search into what specific addresses (or entries) trigger the error, but anecdotally it seems to trigger more for shipping addresses in Asia (Hong Kong, other parts of China, Taiwan, etc).

However, my argument for inclusion is simple: PayPal allows it as an option, therefor we should allow store owners to change this setting if they choose.

I plan on implementing a simple filter so that it will default to 1, but can be overridden in cases where it's not needed.

**Comment by jonathandavis** [comment]
@crunnells When do you think you can submit the PR for this?

**Comment by crunnells** [comment]
By tomorrow

**Comment by jonathandavis** [comment]
Huzzah! :beers:

**Comment by crunnells** [comment]
Closing since the PR has been submitted (a week late).
