### ISSUE TITLE
Label position inconsistency

### ISSUE THREAD

**Issue by ben72** [ingenesis/shopp#3305]
The labels on the checkout field are above the input fields. But on the profile page they are still below. This is confusing especially as the labels are aligned vertically to sit just above the field below even though they belong to the field above!

Here they should also be placed above like on the checkout page:
/shop/account/?profile

See screenshot:
https://www.dropbox.com/s/cnhyxq67hdpcme3/Selection_235.jpg?dl=0

Related to #2185

**Comment by jonathandavis** [comment]
Agreed, you should do a PR and fix it. :P It's a simple move of the `<label>` lines in the template.
