### ISSUE TITLE
German Currency format is incorrect in Lookup.php

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3306]
In Lookup.php Germany is shown with a point rather than a comma before the decimal place. This is wrong http://en.wikipedia.org/wiki/Decimal_mark (and a Shopp merchant).

**Comment by sierrab123** [comment]
I would make a PR if I could

**Comment by jonathandavis** [comment]
Wikipedia is not an accurate, or authoritative source for this sort of information. Do you have other sources that corroborate the comma-decimal usage in Germany?

**Comment by sierrab123** [comment]
http://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html

**Comment by sierrab123** [comment]
Closed with PR https://github.com/ingenesis/shopp/pull/3307
