### ISSUE TITLE
Shopp Plugin shipping cost to continents countries

### ISSUE THREAD

**Issue by Raman16** [ingenesis/shopp#3310]
I need little help regaring shopp plugin, In My shopp plugin-->Shipping,I have set Continents in Destination with shipping cost,But the shipping cost is not available to all the countries under the continent in the cart page   and also let me know this issue will be fixed with above thing..."The order cannot be processed. No shipping is available to the address you provided. Please return to checkout and try again".
I m new to shopp plugin
Please some one help me how to fix it,Thanks in advance

**Comment by sierrab123** [comment]
Hi Raman,

You have posted to the wrong place, try the Shopp Community forum https://shopplugin.net/support/forum/community-support/ or the support Help Desk https://shopplugin.net/support/forum/help-desk or the Word Press support for Shopp

I I am not sure where Continents comes from as it does not appear in my drop down listing.

Post your question in any of those 3 places and you will receive Help

**Comment by Raman16** [comment]
Sorry for posting in wrong place,but my issue  is that in shipping[system] in Destination i fixed Asia with some shipping cost, under Asia we have countries like India ,pakistan, Afghanistan. Here in cart page i could not find any shipping cost for india,afghanistan,srilanka and so on,and at same time could see pakistan 's estimated shipping cost...need an uregent help....

**Comment by sierrab123** [comment]
Raman,

Post in the right place and you will get an answer. This not a Shopp issue but a support Issue. Check the documentation https://shopplugin.net/docs/
We answer support issues quickly if you post in the right place

Tell me where you have posted after you have done so

**Comment by Raman16** [comment]
I M really Sorry,I m just new to this.thnks for reply and I found the answer myself

**Comment by sierrab123** [comment]
Raman,

Just use the right places to post a question and you will get loads of help, make a note of those links above
