### ISSUE TITLE
1.4 dev Categories and Product issues

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3316]
Latest Master installed on WAMP locally, fresh install, no other plugins.

1) Unable to save a category, on "Save" page goes blank and nothing is saved
2) On the product admin page, pricing does not appear, replaced by spinning rectangle. However I can save the product

**Comment by sierrab123** [comment]
Using XAMPP the product editor shows as http://awesomescreenshot.com/08b4zy2r94
The Select Markets appears as full list rather than within a dialog box

**Comment by sierrab123** [comment]
The difference between Master and 1.3.9 is as follows:-
Master has 4 more files,
style.php in  api/ 
Styles.php in core/flow/
ShoppServices.php in core/library
styles.php in services/
That's what seems to be causing the issue
Apart from that the 2 folders are identical

**Comment by sierrab123** [comment]
Checking out these 4 files in Master I find that all four have been double reverted i.e. it says  	Revert "Revert " in their descriptions. I am not sure of the impact of this on them. However there are other files that have been similarly "double reverted" with seemingly no issues

**Comment by jonathandavis** [comment]
It appears you have major style issues. Most likely because ShoppServices is not being invoked properly.

**Comment by sierrab123** [comment]
As suggested, downloaded latest product editor screen branch, tested on WAMP and on-line, this issue continues.
