### ISSUE TITLE
Order does not always lead to a new entry in cusomer/address tables

### ISSUE THREAD

**Issue by ben72** [ingenesis/shopp#3324]
A symptom of this is that the shipping fields are not collapsible on the order page in the back-end.

And no entry in shopp_customer or shopp_address can be found.

This does not seem to happen often but I think it needs looking into. I've seen it on two different installs.

(order#2411 for my own reference)

**Comment by sierrab123** [comment]
I have just seen this on another install. It appears to happen at random. It is not possible to edit and update the shipping fields and as ben said the shipping fields remain open rather than collapsed in the order admin page

**Comment by ben72** [comment]
I think it has to do with the order event handling. In these cases I think there has been multiple Payment received events so the balance is not 0. And when I've removed the extra entries in the meta table the issue with the non-collapsed address field has resolved.

**Comment by sierrab123** [comment]
The problem is that the issue can just keep re-generating, even after the work-around, I have the same issue back, at random.

**Comment by StitchsLoft** [comment]
I been having same issue its totally random, often will let you perform an update but will still not close the edit box... These type bugs cause issues when trying to complete out orders for customers.
