### ISSUE TITLE
jvectormap in reporting

### ISSUE THREAD

**Issue by dxdc** [ingenesis/shopp#3336]
Few minor issues in jvectormap under Reporting for admin panel:

1. French Guinea (south america) and France are being referred to as the same country when you hover over the map. Is this the intended behavior? This is wrong on http://jvectormap.com/ as well.

2. Vietnam is being reported as VI in the list and not appearing as its name / or with sales reported to Vietnam. I traced this bug back to the country list on the checkout page... this is also the same country code as Virgin Islands (which is the correct code). Strangely, it's just listed as "VI" in the Country list with no other explanation.

![7-6-2015 2-29-07 pm](https://cloud.githubusercontent.com/assets/7200365/8531214/62d35042-23eb-11e5-8b74-59dbc3f4751b.jpg)
![7-6-2015 2-29-38 pm](https://cloud.githubusercontent.com/assets/7200365/8531223/74404c9a-23eb-11e5-88de-ed4e57a626e5.jpg)

**Comment by msigley** [comment]
I would suggest opening an issue for "France" issue on the jvectormap repo:
https://github.com/bjornd/jvectormap

We will look into the "Vietnam" issue.

**Comment by dxdc** [comment]
Thanks... found this existing bug report + solution:

https://github.com/bjornd/jvectormap/issues/329

**Comment by sierrab123** [comment]
Somewhat bizarrely French Guiana (South America) and France are actually same country, FG is a dept of France.

French Guinea (West Africa) was another country and is now known as Guinea an independent country

**Comment by dxdc** [comment]
Sorry... I meant "Guiana" not "Guinea" in my original post. It's listed as a separate country in the dropdown during checkout, which is why I asked about it, though I guess it's OK if it's bundling sales in the jvectormap. It's part of France but at the same time has it's own flag, capital, etc. Very confusing @sierrab123 !

Another strange feature is that the dropdown list of countries during checkout is sorted into different categories by Shopp. E.g. Algeria appears after US Armed Forces. Is there any way to change that to have it all sort into a single list (maybe leaving USA, Canada, UK at the top as is done currently)?

Thanks all.

**Comment by sierrab123** [comment]
To clear up the confusion check out wikipedia on all the variations of Guiana and Guinea, a nightmare.

The reason that US Armed forces appears directly after USA and before Algeria is that Fed Ex and UPS and USPS all treat freight to the US Forces and US territories in the same(ish) way as the US (in most cases) At least I think that is the reason. Also Shopp was built by American devs!!! They have a different sense of geography to the rest of us.

**Comment by sierrab123** [comment]
I just looked up Vietnam in Shopp/core/Lookup.php and the code is given as VND, so this looks again if it is down to the map

**Comment by dxdc** [comment]
It's definitely confusing indeed. I'm trying to simplify my setup for intl buyers so having multiple groups of sorted countries I imagine is confusing as well. My intl business is growing to near 50% of total so these issues are becoming more important to me. 

Vietnam was correct in the lookup.php but reporting as VI in the checkout page. Maybe in SQL tables...not sure where that's being populated from.  Is this because I've upgraded from an earlier version of Shopp?

**Comment by sierrab123** [comment]
I have just run a test on my site and purchased as from Vietnam. Everything, checkout, orders and location reports panned out correctly, no sign of VI

**Comment by dxdc** [comment]
![7-7-2015 11-20-01 am](https://cloud.githubusercontent.com/assets/7200365/8551100/2c2ff40a-249a-11e5-909f-244af6d38c14.jpg)

Do you see something different than this?

**Comment by sierrab123** [comment]
I see VN not VI.

AS this looks as if it is just an issue on your site rather than an issue as such, could we move this to the Community Forum or the Help Desk as that is more suited to this type of problem

**Comment by dxdc** [comment]
@sierrab123, I imagine I'm not the only person with this issue. How could it be VI in just my installation, when the only thing I've done is select/deselect countries?

Could be due to an upgrade from 1.0.18 perhaps?

**Comment by sierrab123** [comment]
I suggest that you delete the current shopp plugin and install a new one. Maybe you have some remnants of the old one....I have no idea. No one else has reported this issue.

**Comment by dxdc** [comment]
thanks @sierrab123 . I'll investigate. Any clue where this VI is being populated from? I couldn't find it in any of the Shopp plugin files. I suspect the SQL db but haven't looked yet.

**Comment by sierrab123** [comment]
The only VI I could see was a province in Italy!

**Comment by crunnells** [comment]
@dxdc Check in your wp_shopp_meta table, look for 'target_markets' under the name column, and that's an array of the target market countries. It might be that VI is stuck in there instead of VN, so I'd look there first. 

Also, the reason that Algeria appears after US Armed Forces is probably the order of the array mentioned above. It doesn't sort the list automatically, and in my experience it lists countries in the order that you added them to your target markets. Otherwise, you can sort this list using a filter.

**Comment by dxdc** [comment]
thanks! I'll check that out later this week and report back.

**Comment by dxdc** [comment]
The issue was as @crunnells pointed out in the target_markets table. Vietnam was there, listed as VI. It must have been wrong in an earlier Shopp installation? There's no other explanation I can think of. Anyhow, fixed now.

I also appreciate your detailed blog post on sorting the country list using filters. That's a nice trick, especially if you're going to be continually adding/removing countries. The only downside is it doesn't give you the flexibility to leave the home country (e.g. USA) or commonly ordered from countries sorted at the top.

Since I have all countries enabled, I did some fancy grep and sorted the values right inside the SQL table. I hope some of my other country codes are not wrong from legacy Shopp installations, but time will tell about that. I have all target markets selected. In case anyone wants to copy/paste these values into their Shopp install, pre-sorted, here they are. Only US Canada and UK are left at the top of the list... so you could sort those appropriately within this if you wanted.

```
a:244:{s:2:"US";s:3:"USA";s:2:"CA";s:6:"Canada";s:2:"GB";s:14:"United Kingdom";s:2:"AF";s:11:"Afghanistan";s:2:"AX";s:14:"Åland Islands";s:2:"AL";s:7:"Albania";s:2:"DZ";s:7:"Algeria";s:2:"AS";s:14:"American Samoa";s:2:"AD";s:7:"Andorra";s:2:"AO";s:6:"Angola";s:2:"AI";s:8:"Anguilla";s:2:"AG";s:19:"Antigua and Barbuda";s:2:"AR";s:9:"Argentina";s:2:"AM";s:7:"Armenia";s:2:"AW";s:5:"Aruba";s:2:"AU";s:9:"Australia";s:2:"AT";s:7:"Austria";s:2:"AZ";s:10:"Azerbaijan";s:2:"BS";s:7:"Bahamas";s:2:"BH";s:7:"Bahrain";s:2:"BD";s:10:"Bangladesh";s:2:"BB";s:8:"Barbados";s:2:"BY";s:7:"Belarus";s:2:"BE";s:7:"Belgium";s:2:"BZ";s:6:"Belize";s:2:"BJ";s:5:"Benin";s:2:"BM";s:7:"Bermuda";s:2:"BT";s:6:"Bhutan";s:2:"BO";s:7:"Bolivia";s:2:"BA";s:22:"Bosnia and Herzegovina";s:2:"BW";s:8:"Botswana";s:2:"BR";s:6:"Brazil";s:2:"IO";s:30:"British Indian Ocean Territory";s:2:"VG";s:22:"British Virgin Islands";s:2:"BN";s:17:"Brunei Darussalam";s:2:"BG";s:8:"Bulgaria";s:2:"BF";s:12:"Burkina Faso";s:2:"MM";s:5:"Burma";s:2:"BI";s:7:"Burundi";s:2:"KH";s:8:"Cambodia";s:2:"CM";s:8:"Cameroon";s:2:"CV";s:10:"Cape Verde";s:2:"KY";s:14:"Cayman Islands";s:2:"CF";s:24:"Central African Republic";s:2:"TD";s:4:"Chad";s:2:"CL";s:5:"Chile";s:2:"CN";s:5:"China";s:2:"CX";s:16:"Christmas Island";s:2:"CC";s:23:"Cocos (Keeling) Islands";s:2:"CO";s:8:"Colombia";s:2:"KM";s:7:"Comoros";s:2:"CG";s:17:"Congo-Brazzaville";s:2:"CD";s:14:"Congo-Kinshasa";s:2:"CK";s:12:"Cook Islands";s:2:"CR";s:10:"Costa Rica";s:2:"CI";s:14:"Côte d'Ivoire";s:2:"HR";s:7:"Croatia";s:2:"CU";s:4:"Cuba";s:2:"CW";s:8:"Curaçao";s:2:"CY";s:6:"Cyprus";s:2:"CZ";s:14:"Czech Republic";s:2:"DK";s:7:"Denmark";s:2:"DJ";s:8:"Djibouti";s:2:"DM";s:8:"Dominica";s:2:"DO";s:18:"Dominican Republic";s:2:"TL";s:10:"East Timor";s:2:"EC";s:7:"Ecuador";s:2:"EG";s:5:"Egypt";s:2:"SV";s:11:"El Salvador";s:2:"GQ";s:17:"Equatorial Guinea";s:2:"ER";s:7:"Eritrea";s:2:"EE";s:7:"Estonia";s:2:"ET";s:8:"Ethiopia";s:2:"FK";s:16:"Falkland Islands";s:2:"FO";s:13:"Faroe Islands";s:2:"FM";s:30:"Federated States of Micronesia";s:2:"FJ";s:4:"Fiji";s:2:"FI";s:7:"Finland";s:2:"FR";s:6:"France";s:2:"GF";s:13:"French Guiana";s:2:"PF";s:16:"French Polynesia";s:2:"TF";s:21:"French Southern Lands";s:2:"GA";s:5:"Gabon";s:2:"GM";s:6:"Gambia";s:2:"GE";s:7:"Georgia";s:2:"DE";s:7:"Germany";s:2:"GH";s:5:"Ghana";s:2:"GI";s:9:"Gibraltar";s:2:"GR";s:6:"Greece";s:2:"GL";s:9:"Greenland";s:2:"GD";s:7:"Grenada";s:2:"GP";s:10:"Guadeloupe";s:2:"GU";s:4:"Guam";s:2:"GT";s:9:"Guatemala";s:2:"GG";s:8:"Guernsey";s:2:"GW";s:13:"Guinea-Bissau";s:2:"GN";s:6:"Guinea";s:2:"GY";s:6:"Guyana";s:2:"HT";s:5:"Haiti";s:2:"HM";s:26:"Heard and McDonald Islands";s:2:"HN";s:8:"Honduras";s:2:"HK";s:9:"Hong Kong";s:2:"HU";s:7:"Hungary";s:2:"IS";s:7:"Iceland";s:2:"IN";s:5:"India";s:2:"ID";s:9:"Indonesia";s:2:"IR";s:4:"Iran";s:2:"IQ";s:4:"Iraq";s:2:"IE";s:7:"Ireland";s:2:"IM";s:11:"Isle of Man";s:2:"IL";s:6:"Israel";s:2:"IT";s:5:"Italy";s:2:"JM";s:7:"Jamaica";s:2:"JP";s:5:"Japan";s:2:"JE";s:6:"Jersey";s:2:"JO";s:6:"Jordan";s:2:"KZ";s:10:"Kazakhstan";s:2:"KE";s:5:"Kenya";s:2:"KI";s:8:"Kiribati";s:2:"KW";s:6:"Kuwait";s:2:"KG";s:10:"Kyrgyzstan";s:2:"LA";s:4:"Laos";s:2:"LV";s:6:"Latvia";s:2:"LB";s:7:"Lebanon";s:2:"LS";s:7:"Lesotho";s:2:"LR";s:7:"Liberia";s:2:"LY";s:5:"Libya";s:2:"LI";s:13:"Liechtenstein";s:2:"LT";s:9:"Lithuania";s:2:"LU";s:10:"Luxembourg";s:2:"MO";s:5:"Macau";s:2:"MK";s:9:"Macedonia";s:2:"MG";s:10:"Madagascar";s:2:"MW";s:6:"Malawi";s:2:"MY";s:8:"Malaysia";s:2:"MV";s:8:"Maldives";s:2:"ML";s:4:"Mali";s:2:"MT";s:5:"Malta";s:2:"MH";s:16:"Marshall Islands";s:2:"MQ";s:10:"Martinique";s:2:"MR";s:10:"Mauritania";s:2:"MU";s:9:"Mauritius";s:2:"YT";s:7:"Mayotte";s:2:"MX";s:6:"Mexico";s:2:"MD";s:7:"Moldova";s:2:"MC";s:6:"Monaco";s:2:"MN";s:8:"Mongolia";s:2:"ME";s:10:"Montenegro";s:2:"MS";s:10:"Montserrat";s:2:"MA";s:7:"Morocco";s:2:"MZ";s:10:"Mozambique";s:2:"NA";s:7:"Namibia";s:2:"NR";s:5:"Nauru";s:2:"NP";s:5:"Nepal";s:2:"NL";s:11:"Netherlands";s:2:"NC";s:13:"New Caledonia";s:2:"NZ";s:11:"New Zealand";s:2:"NI";s:9:"Nicaragua";s:2:"NE";s:5:"Niger";s:2:"NG";s:7:"Nigeria";s:2:"NU";s:4:"Niue";s:2:"NF";s:14:"Norfolk Island";s:2:"MP";s:24:"Northern Mariana Islands";s:2:"NO";s:6:"Norway";s:2:"OM";s:4:"Oman";s:2:"PK";s:8:"Pakistan";s:2:"PW";s:5:"Palau";s:2:"PA";s:6:"Panama";s:2:"PG";s:16:"Papua New Guinea";s:2:"PY";s:8:"Paraguay";s:2:"PE";s:4:"Peru";s:2:"PH";s:11:"Philippines";s:2:"PN";s:16:"Pitcairn Islands";s:2:"PL";s:6:"Poland";s:2:"PT";s:8:"Portugal";s:2:"PR";s:11:"Puerto Rico";s:2:"QA";s:5:"Qatar";s:2:"RE";s:8:"Réunion";s:2:"RO";s:7:"Romania";s:2:"RU";s:6:"Russia";s:2:"RW";s:6:"Rwanda";s:2:"BL";s:17:"Saint Barthélemy";s:2:"SH";s:12:"Saint Helena";s:2:"KN";s:21:"Saint Kitts and Nevis";s:2:"LC";s:11:"Saint Lucia";s:2:"MF";s:12:"Saint Martin";s:2:"PM";s:25:"Saint Pierre and Miquelon";s:2:"VC";s:13:"Saint Vincent";s:2:"WS";s:5:"Samoa";s:2:"SM";s:10:"San Marino";s:2:"ST";s:24:"São Tomé and Príncipe";s:2:"SA";s:12:"Saudi Arabia";s:2:"SN";s:7:"Senegal";s:2:"RS";s:6:"Serbia";s:2:"SC";s:10:"Seychelles";s:2:"SL";s:12:"Sierra Leone";s:2:"SG";s:9:"Singapore";s:2:"SX";s:12:"Sint Maarten";s:2:"SK";s:8:"Slovakia";s:2:"SI";s:8:"Slovenia";s:2:"SB";s:15:"Solomon Islands";s:2:"SO";s:7:"Somalia";s:2:"ZA";s:12:"South Africa";s:2:"GS";s:13:"South Georgia";s:2:"KR";s:11:"South Korea";s:2:"SS";s:11:"South Sudan";s:2:"ES";s:5:"Spain";s:2:"LK";s:9:"Sri Lanka";s:2:"SD";s:5:"Sudan";s:2:"SR";s:8:"Suriname";s:2:"SJ";s:22:"Svalbard and Jan Mayen";s:2:"SZ";s:9:"Swaziland";s:2:"SE";s:6:"Sweden";s:2:"CH";s:11:"Switzerland";s:2:"SY";s:5:"Syria";s:2:"TW";s:6:"Taiwan";s:2:"TJ";s:10:"Tajikistan";s:2:"TZ";s:8:"Tanzania";s:2:"TH";s:8:"Thailand";s:2:"TG";s:4:"Togo";s:2:"TK";s:7:"Tokelau";s:2:"TO";s:5:"Tonga";s:2:"TT";s:19:"Trinidad and Tobago";s:2:"TN";s:7:"Tunisia";s:2:"TR";s:6:"Turkey";s:2:"TM";s:12:"Turkmenistan";s:2:"TC";s:24:"Turks and Caicos Islands";s:2:"TV";s:6:"Tuvalu";s:2:"UG";s:6:"Uganda";s:2:"UA";s:7:"Ukraine";s:2:"AE";s:20:"United Arab Emirates";s:2:"UY";s:7:"Uruguay";s:4:"USAF";s:15:"US Armed Forces";s:4:"USAT";s:14:"US Territories";s:2:"UZ";s:10:"Uzbekistan";s:2:"VU";s:7:"Vanuatu";s:2:"VA";s:12:"Vatican City";s:2:"VE";s:9:"Venezuela";s:2:"VN";s:7:"Vietnam";s:2:"WF";s:17:"Wallis and Futuna";s:2:"EH";s:14:"Western Sahara";s:2:"YE";s:5:"Yemen";s:2:"ZM";s:6:"Zambia";s:2:"ZW";s:8:"Zimbabwe";}
```

**Comment by crunnells** [comment]
If nothing else this identifies another issue which is that we should be sorting the countries before saving them to the database. I know there are situations where you'll want your home country to appear at the top of the list, but as we just demonstrated it's not that difficult to do. I'll see if I can work up a PR this week.

**Comment by dxdc** [comment]
I agree with that, maybe only that the home country should stay on top though. Thanks @crunnells!

I think it would be good to also verify this country list against the official internal Shopp db if at all possible. Seems like a small risk to generate a separate list like this which is not tied to the official db.

**Comment by sierrab123** [comment]
Now duplicated by current dev
