### ISSUE TITLE
Hook to listen to coupon code applied

### ISSUE THREAD

**Issue by sobytes** [ingenesis/shopp#3337]
Hi All,

I need to have a discount code to allow the first month of a subscription half price.

The only way i can think to do this is to hook into the apply discount code and then switch products to one that has a trial period 1 month and discount half price applied.

I cant find a hook to listen to when somebody applies a certain discount code if it matches then update the cart with a discounted product.

https://shopplugin.net/api/category/develop

Is there a hook available for this thanks

**Comment by msigley** [comment]
These issues are for bug reports and feature requests. Please direct your support question to the free support forums on Wordpress.org or to the paid support Helpdesk on shopplugin.net:
https://wordpress.org/support/plugin/shopp
https://shopplugin.net/support/
