### ISSUE TITLE
Shopp causes occasional Fatal Error when opening the dasboard

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3342]
WP 4.22
Shopp 1.3.9
I have just started to get this random error appearing on one of my own web sites when I open the wp-admin. I wait a few moments and the issue goes away          Fatal error: Nesting level too deep - recursive dependency? in /home/peebee/2015_html/wp-content/plugins/shopp/core/library/Modules.php on line 177 .

This appears to be a PHP error generated by shopp .There is a 'fix' which is to replace a '==' with a single equals in the line of the file the error quotes. I had a look at the offending file as quoted by that error, but couldn't see an appropriate bit to edit.

**Comment by clifgriffin** [comment]
@sierrab123 That "fix" sounds dubious to me :)

You say it doesn't happen all the time, just the first few page loads?

**Comment by sierrab123** [comment]
@clifgriffin as you probably guessed it was not my idea but that of my host! It does not happen all the time when I go to the dashboard. Today I can't recreate and can move around the site with no issue.

PHP 5.3.3-7+squeeze26 with Suhosin-Patch (cli) (built: Apr 29 2015
09:25:24)

**Comment by clifgriffin** [comment]
Yeah, I've seen hosts complain about recursion in Shopp. I'm wondering if there is a real issue here that is hiding except on very picky hosts.

**Comment by sierrab123** [comment]
Been with this host since 2009/10 first time I have seen this. If it occurs again I will report it

**Comment by sierrab123** [comment]
Not had this happen since I last reported, so I am going to close it
