### ISSUE TITLE
Shopp 1.4dev causes fatal error on Activation

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3346]
Both on a WAMPP install and an on-line install I get the same error when trying to activate.

This is with the latest Master downloaded at 12.30 July 14

Both sites running the latest WP 4.2.2

( ! ) Fatal error: Class 'ImageSetting' not found in C:\wamp\www\Shopp140\wp-content\plugins\shopp\api\settings.php on line 147
Call Stack
#	Time	Memory	Function	Location
1	0.0020	251168	{main}( )	..\plugins.php:0
2	1.2747	20438024	do_action( )	..\plugins.php:157
3	1.2747	20438968	call_user_func_array:{C:\wamp\www\Shopp140\wp-includes\plugin.php:496} ( )	..\plugin.php:496
4	1.2747	20439008	ShoppFlow->activate( )	..\plugin.php:496
5	1.2814	20660800	do_action( )	..\Flow.php:139
6	1.2815	20661856	call_user_func_array:{C:\wamp\www\Shopp140\wp-includes\plugin.php:496} ( )	..\plugin.php:496
7	1.2815	20661952	ShoppInstallation->activate( )	..\plugin.php:496
8	1.3214	21797120	do_action( )	..\Install.php:74
9	1.3214	21798296	call_user_func_array:{C:\wamp\www\Shopp140\wp-includes\plugin.php:496} ( )	..\plugin.php:496
10	1.3215	21798648	ShoppInstallation->setup( )	..\plugin.php:496
11	1.3227	21798752	ShoppInstallation->images( )	..\Install.php:433
12	1.3276	21992816	shopp_set_image_setting( )	..\Install.php:358

**Comment by jonathandavis** [comment]
@sierrab123 This is waiting on a review of #3344

**Comment by jonathandavis** [comment]
#3344 was merged.
