### ISSUE TITLE
How To Infinitely Speed Up Large Purchase Exports With Add-ons

### ISSUE THREAD

**Issue by clifgriffin** [ingenesis/shopp#3354]
A client was trying to export 5,000 orders, including add-on info. The query was trashing MySQL so bad that all the websites on the server would become unresponsive and the export would never start.

I found that adding this `INDEX`, fixed everything:
``` sql
ALTER TABLE wp_shopp_meta ADD INDEX meta_type_context(`type`,`context`)
```

This dropped the query time to < 1 second. 

We should add this, or a similar index to 1.4 and also evaluate whether or not there are any other indexes that should be considered for `shopp_meta`, given how large it is will grow over time. 

Assining to @jonathandavis since he's the wizard behind the Shopp schema, and likely understands INDEXES better than most of us. :-)

**Comment by jonathandavis** [comment]
This looks like it was taken care of already. @clifgriffin Can you confirm?

**Comment by clifgriffin** [comment]
@jonathandavis Yup, looks like it. Closing.
