### ISSUE TITLE
Transferring images from FSS to S3

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3358]
I have been looking at this for the last few days and could not find the correct spot to assemble all the bits and pieces

For merchants who have a large image set, the transfer to S3 presents a real nightmare. You can't just upload all the images to S3 and then point Shopp at them in Shopp/System/Storage which would be ideal

Nor is there an equivalent of the migrate images tools that Barry and Adam wrote

Ways of dealing with this include the following:-
"I think more likely if I was doing it I'd go for a lazy, just in time approach: the template tags for product/store images provide a ton of hooks, so it seems like you could catch ones still being served from the db (or from the fss, or from anything that isn't S3) and let it process as normal so as not to hold things up - but fire off a service request to copy it to S3 and then update the references in the db

so you'd basically have an ongoing, auto-magical transfer"

first time, it's still served from the file system. Second time, it will have been moved "to S3

Next up was:-
Legitimately reupload one of the images to amazons3 through shopp on a new empty bucket to see the file format they are being stored in

then if any filename changes need to occur it could probably be accomplished with a shell/bash/batch/powershell script locally

OR

in theory you should be able to mount your s3 bucket as a netdrive on your server and use a folder alias to redirect the shopp product image folder to the bucket

Any other thoughts on how to accomplish this gratefully received.

Of course a new plugin would be really cool

**Comment by crunnells** [comment]
As long as the image names are the same on the FSS as they are on Amazon (which, they should be), all you should need to do is upload all of the images to the bucket, then update the wp_shopp_meta records for those images to point to AmazonS3 instead of local storage.

**Comment by sierrab123** [comment]
Unfortunately, this does not appear to work I swapped the FSS to AmazonS3 and added the bucket name as in the example that I had used previously

These are the  3 examples from the db 1 from Amazon which I strated with and then I used the same image on the next products. 

This is obviously doable as Barry and Adam must have something in place that does the same sort of thing
O:8:"stdClass":10:{s:4:"mime";s:10:"image/jpeg";s:4:"size";i:29702;s:7:"storage";s:8:"AmazonS3";s:3:"uri";s:20:"shopptest2:aroma.jpg";s:8:"filename";s:9:"aroma.jpg";s:5:"width";i:272;s:6:"height";i:398;s:3:"alt";N;s:5:"title";N;s:8:"settings";N;}

O:8:"stdClass":10:{s:4:"mime";s:10:"image/jpeg";s:4:"size";i:29702;s:7:"storage";s:9:"FSStorage";s:3:"uri";s:11:"aroma-1.jpg";s:8:"filename";s:11:"aroma-1.jpg";s:5:"width";i:272;s:6:"height";i:398;s:3:"alt";N;s:5:"title";N;s:8:"settings";N;}

O:8:"stdClass":10:s:4:"mime";s:10:"image/jpeg";s:4:"size";i:29702;s:7:"storage";s:9:"FSStorage";s:3:"uri";s:9:"aroma.jpg";s:8:"filename";s:9:"aroma.jpg";s:5:"width";i:272;s:6:"height";i:398;s:3:"alt";N;s:5:"title";N;s:8:"settings";N;}

**Comment by sierrab123** [comment]
After more expts I noticed that the problem lay in the seemingly random nature of the "s" after "filename" which flummoxed me!  @crunnells  rode to the rescue again and I quote,

"Without going into too much detail, the letters and numbers describe the type and length of the data. So, a string for Hello World would be s:11:"Hello World" because there are 11 characters (counting the space)

So when you change the "uri" to include the bucket name, you need to increase the character count to accommodate the extra letters. Otherwise json decides it's bad data because the data doesn't match what it's expecting. It's better to do this programmatically rather than manually, because it's easy to make mistakes

That's the only real difference is the URI and storage fields, changing those would do it. Like I said, it would have to be done individually because MySQL can't decode the json data automatically, so you'd need to read the line into PHP, decode the json, change those fields, then encode and save the data to MySQL. One entry at a time.
Wouldn't take much to whip up a plugin to do that

**Comment by sierrab123** [comment]
Can confirm this works manually. I am just wondering if it could be done purely by an SQL query

This part of the value is all that needs to be changed 

9:"FSStorage";s:3:"uri";s:21:"
to
8:"AmazonS3";s:3:"uri";s:32:"shopptest2:

The number before shopptest2, in this example needs to have 8 added to it in every instance (the number of the alphanumeric characters in the name of the bucket, in this case shopptest2)

The only issue I can report with having made the change manually is the image does not seem to show up on the Products page in admin, although it does show up in the product editor and on the front page, although it does not expand like the product image that I added to Shopp when it was set to store in Amazon, although I can probably make this work when I have a little more time

**Comment by sierrab123** [comment]
The missing image issue was caused by the cached image entries in the shopp-meta table. I deleted all the cached info from the db and the cached images both in Amazon and the site image folder and in addition deleted cached images from within Shopp (System Advanced) (Nothing like making sure!!)

Result Perfection

**Comment by sierrab123** [comment]
Solved! I have a perl script that will convert the db entries for FSS to Amazon S3 taking care of the changed string length. I will put it up at Git Hub

**Comment by sierrab123** [comment]
Someone should do this perl script in php as a plugin or incorporate it into the Amazon S3 plugin
