### ISSUE TITLE
shopp('product.processing')

### ISSUE THREAD

**Issue by AlbertBoddema** [ingenesis/shopp#3371]
I was looking for an option to display the processing time in the product.php template.
But this option seems not to exist.
This is strange because there is option to enter this information when you add an product.
![settings](https://cloud.githubusercontent.com/assets/4806294/9771231/08da17d8-5735-11e5-8e46-ad1e3deec8ab.jpg)
I'm looking for an shopp('product.processing') and shopp('product.has-processing') to display the processing time and to check if there is an time to display an message

**Comment by meredevelopment** [comment]
I have a need for this, I'd be interested in adding it or exposing it some other way also. I can have a look tomorrow as I'll be working on a project that makes use of a products processing time to display different messages in Cart and Checkout. Watch this space...

**Comment by jonathandavis** [comment]
Merged.
