### ISSUE TITLE
Checkout issues with fields in submit function

### ISSUE THREAD

**Issue by Boxedsolutions** [ingenesis/shopp#3375]
Background: I want to add a field for Social Security number, for processing with payment gateway. 

But i Found this line in ui/behaviour/checkout.js which make it impossible without changing the core files. 
submitButtons = checkoutButtons.find('input'),

Wouldnt it be smart to add .not('.ignore-submit') or something so the line become?
submitButtons = checkoutButtons.find('input').not('.ignore-submit'),

That way it should be possible to add fields that not is triggered by click.

**Comment by Just-m** [comment]
There is a function to grab additional information at checkout. Would that work for you?
https://shopplugin.net/api/checkout-customer-info/

**Comment by Boxedsolutions** [comment]
No, Its a Payment Gateway and we do not want to modify our Clients templates, 

Its better for us to just use the submit function to add a field, and if it possible to add a ignore class in the core, it would probably be the right way to do this.

**Comment by Just-m** [comment]
I am not completely sure what you are trying to do but I think everything you need is already present.

You could use `add_filter('shopp_checkout_gateway_inputs', array($this, 'your_function'));`
In `your_function` create an `array $markup` holding the html lines you want to add. `your_function` should return `$options.join('',$markup);` to add the html to the page

You can add additional scripting the same way using `array $script` and `add_storefrontjs(join("\n",$script));` in `your_function`
