### ISSUE TITLE
Discount on categories with & in name does not work

### ISSUE THREAD

**Issue by ben72** [ingenesis/shopp#3383]
1. Setup a Cart item discount for a category named:
   "Ekologiska klänningar & tunikor"
   with a discount code.
2. Add an item in that category to the cart.
3. Try to apply the discount code.
   Nothing happens!
4. Try to apply the code again.
   It says it's already used but no discount is showing.

Try the same with a category named:
"Ekologiska klänningar + tunikor".
This time it works!

**Comment by Just-m** [comment]
I see the same mismatch

**Comment by Just-m** [comment]
Fixed by #3660
