### ISSUE TITLE
'value' option does not work for checkout.billing-address (and others)

### ISSUE THREAD

**Issue by mwendell** [ingenesis/shopp#3384]
I just spent a few hours trying to figure out what might be wrong in my code. I'm inserting fields into my checkout page like this...

    shopp('checkout','billing-city','required=true&title=City billing address&value='.$u->billing_city);

...where $u->billing_city is the default value I expect to be displayed in the field. no matter what I tried, the default value is NOT displayed.

I also tried doing it this way...

    shopp('checkout.billing-address', array('required' => 1, 'title' => 'Billing Address', 'label' => $u->billing_address, 'value' => $u->billing_address));

...and again, $u->billing_address is a valid default value that should be applied to the field in question using the value attribute, as described in your documentation. For example [this page](https://shopplugin.net/api/checkout-billing-name/) lists default form input options that apply to "theme api calls that output form input tags". Value is an accepted input option, but it doesn't seem to work.

Some of the fields work just fine, just as expected with the value option. First_name, last_name, user_email, phone, and organization return the defaults perfectly if a value is supplied. For example...

    shopp('checkout','phone','required=true&format=phone&size=15&title=Phone&value='.$u->phone);

... works just fine on our form. Exactly as expected, and as you see, the code is identical to the code that doesn't work.

I went hunting in your code to see how phone and email handling might be different from address handling. Eventually I found that by disabling a few lines I could make the value option work.

To make the value option work for billing_address, billing_xaddress, billing_city, shipping_address, shipping_xaddress, and shipping _city (and probably more, but those are all I tried), I had to disable the following lines 1772 and 1773 from /plugins/shopp/api/theme/customer.php...

    // if ( ! property_exists($Address, $options['property']) ) $options['property'] = 'address';
    // $options['value'] = $Address->{$options['property']};

To make the value option work for billing_state and shipping_state, I disabled line 1854 from the same file...

    // $options['value'] = $Address->state;

In both of these cases it looks like you're overwriting the value that the theme file is sending you in the checkout command. I love that your code has the initiative to find and use address information, but I really think that if the theme file is explicitly sending you a value, then that value should be prioritized over any address data you might find on your own.

I really don't want to be messing with the core parts of your files, but I really need to be able to manipulate and assign the default values for these fields on our checkout page. Do you have another suggestion for a way to make the 'value' option work properly?

m.

**Comment by Just-m** [comment]
These fields should populate automatically after the customer logs in. What else would the purpose of using accounts be? Must be a conflict with your theme or another plugin.

**Comment by mwendell** [comment]
Well, thanks, of course. And my first assumption is always that it's my code, but in this case... I don't think so.

I use the exact same syntax for first_name, last_name, user_email, organization, and phone... and they all work fine.  Only the address fields are broken.

Looking through the Shopp core PHP I found that the address fields are handled differently and seem to be looking for default information elsewhere, as opposed to prioritizing the information submitted to the function.

m.

**Comment by mwendell** [comment]
I think the problem here is that Shopp assumes that the user was created by Shopp. The majority of our users are created outside of Shopp, which means it's critical that I can pass address information gathered elsewhere to the Shopp checkout page.

    shopp('checkout','billing-city','value=my-inserted-value');

Try inserting any random value into the billing city field for example. You can submit default values all day and they won't be reflected in your input field.

The default files work specifically because they don't call the 'value' option. They assume that the user has a Shopp account, and if not, no default information is presented.

The **address** helper function in /shopp/api/theme/customer.php (line 1763) is designed to write the actual input field for the checkout page. It handles the address and xaddress fields for shipping and billing, as well as the city fields. The tenth line of that function, line 1773, explicitly replaces *$options['value']* with *$Address->{$options['property']}*. The code is dumping the user submitted default value, without checking to see if it even exists, and replacing it with the address value associated with the $addresses array, which is populated by calls to ShoppOrder->billing and ShoppOrder->shipping).

    $options['value'] = $Address->{$options['property']};

No matter what you submit for the 'value' option, it will be replaced by Shopp on line 1773. And even worse, Shopp will replace it *even if the Shopp doesn't have a valid value to replace it with!*

A less broken solution would be to, at the very least, check if *$Address->{$options['property']}* isn't empty.

    if (!empty($Address->{$options['property']})) { $options['value'] = $Address->{$options['property']}; }

But even that solution ignores the fact that your developers might have a reason for submitting a value. If I went through the trouble of specifying a value, you should probably use it.

    if (empty($options['value'])) { $options['value'] = $Address->{$options['property']}; }

And if you're *not* going to use it, then at the very least your documentation should state that the 'value' option is unsupported by the address, city, state and country fields.

Also, for the record, the same situation exists on line 1802 in the **country** function and on line 1853 in the **state** function.

m.

**Comment by Just-m** [comment]
It would help to know what the exact workflow is, where the data comes from and where/how/when you want to use it. 

It might be better to add data to the ShoppCustomer object instead of invoking it in other places. Hard to tell without the full story.

**Comment by mwendell** [comment]
The story is that we have a non-Shopp order process for high volume subscription fulfillment. Our sites use Shopp to handle single purchases, typically one-off books or logo merch for the publisher. Generally less than 10% our users will ever make a purchase using Shopp on any our sites, and very, very few (bordering on none) will do so prior to registering for a publication. The result is that, in almost all cases, we have a customers information in wp_usermeta prior to checkout. Additionally, regarding the ShoppCustomer object, it seems like overkill to create Shopp customer records every time someone registers for a publication on our site, since 90% of those users will never touch Shopp.

Now, we can go round and round about whose fault this is, or that my code must be the issue, or that we need to change our order flow, or that maybe it's possible by writing and testing a bunch of new code, or maybe if I just do things in a more Shopp-centric way...

None of that fixes the fact that a documented feature in Shopp does not work.

My previous post outlines a test that clearly shows that Shopp ignores the documented 'value' option when rendering certain input fields on the checkout page (all of the address fields).

That post also presented a clean, developer-friendly way to fix the issue.

Now, ignoring the fact that the Shopp documentation is wrong, can someone explain to me the logic behind not supporting the 'value' option? And if there is no explanation, can we move forward with implementing changes to support it in future versions of Shopp?

m.

**Comment by Just-m** [comment]
I wasn't implying you'd create an account for every customer. All you need to do is something like 
```php
ShoppCustomer($u);
```
before the checkout fields display and Shopp will populate your fields. Assuming your properties are named properly.

**Comment by mwendell** [comment]
That wouldn't be so hard, I'll look into it.

Of course that still doesn't change the fact that Shopp is actually broken, assuming you define broken as "doesn't do what the documentation says it does." This is a bug that needs to be addressed.

Shopp should work as documented, or the documentation should be changed.

m.

**Comment by Just-m** [comment]
Did it work?
I would not say Shopp is broken, I would say the documentation is inaccurate.

**Comment by mwendell** [comment]
I gave it a shot, but it didn't work. We currently have a single set of address fields in usermeta, without the 'billing-' or 'shipping-' prefix, so none of that information came across. At this point, I'm keeping my changes to /shopp/api/theme/customer.php in place, as they work fine.

    //LINE 1773 ('address' function)
    if (empty($options['value'])) { $options['value'] = $Address->{$options['property']}; }

    //LINE 1802 ('country' function)
    if (empty($options['value'])) { $options['value'] = $Address->country; }

    //LINE 1853 ('state' function)
    if (empty($options['value'])) { $options['value'] = $Address->state; }

As for Shopp being broken I have two responses... first, the documentation is as important a part of 'Shopp' as the code is. If the documentation is broken, then Shopp is broken. Second, the functions in /shopp/api/theme/customer.php are clearly designed to look for a value being passed via $options['value'], it's just that, they then ignore it. Nobody codes a function to look for a value, to expect that value, if it was never supposed to be supported in the first place.

At this point, I'd like to ask how hard it would be to incorporate my recommended changes into a future version of the plugin. I think the changes above are preferable, since they prioritize the data that is submitted explicitly by the developer and stick closely to the existing API docs.

If you feel that the ShoppCustomer values should be prioritized over anything the developer is submitting, the changes would be as below:

    //LINE 1773 ('address' function)
    if (!empty($Address->{$options['property']})) { $options['value'] = $Address->{$options['property']}; }

    //LINE 1802 ('country' function)
    if (!empty($Address->country)) { $options['value'] = $Address->country; }

    //LINE 1853 ('state' function)
    if (!empty($Address->state)) { $options['value'] = $Address->state; }

Thanks,
m.

**Comment by Just-m** [comment]
The great thing about Github is, everyone can submit suggestions to optimize/correct the code.

Submit a PM and the lead developer will decide whether or not the suggested changes will make it into the next version.

**Comment by clifgriffin** [comment]
Fixed in 33d097d02a8c73ae8c0962444ea17609f3e31dfe.
