### ISSUE TITLE
Product publish options missing

### ISSUE THREAD

**Issue by clifgriffin** [ingenesis/shopp#3388]
On current master, product publish options are gone.

**Comment by Just-m** [comment]
PHP RECOVERABLE ERROR: Argument 1 passed to ShoppAdminMetabox::__construct() must be an instance of ShoppScreenController, string given, called in /home/blank/domains/blank.nl/public_html/supporting/wp-content/plugins/shopp/core/screens/Products.php on line 1177 and defined [UI.php, line 39] ShoppErrors->php, ShoppAdminMetabox->__construct, ShoppScreenProductEditor->layout, ShoppAdminController->layout, call_user_func_array, do_action [UI.php, line 39]

This error shows up in the log on product page load.

**Comment by Just-m** [comment]
I can't find why things go wrong but  with this in /core/Screens/Products.php

```
		new ShoppAdminProductSaveBox(ShoppProduct::posttype(), 'side', 'core', array('Product' => $Product));
```
the save product metabox does not appear on the product-editor page.
Change 'side' to 'normal' and it does show up. Wrong spot of course.
Same goes for product-settings metabox

All ``new ...Box()`` commands generate the error mentioned in my earlier post.

**Comment by Just-m** [comment]
Apparently this has already been fixed in this commit https://github.com/ingenesis/shopp/commit/c8f2f5a74c52205425365098250b8a1295cbeae2 but it is not merged in master.

related issue #3352

**Comment by Just-m** [comment]
fixed in above mentioned commit
