### ISSUE TITLE
Unable to delete image size

### ISSUE THREAD

**Issue by clifgriffin** [ingenesis/shopp#3395]
On current master, unable to delete image sizes.

**Comment by jonathandavis** [comment]
I can no longer reproduce this. I do see a stray "Array" printed on the Images settings admin page.

**Comment by clifgriffin** [comment]
I can confirm that functionally this and #3484 are fixed. However, I also see the stray Array above and below the image sizes table.

**Comment by jonathandavis** [comment]
Ahh… found it. Fix in progress.
