### ISSUE TITLE
Better handle admin notices on settings screen

### ISSUE THREAD

**Issue by clifgriffin** [ingenesis/shopp#3397]
Gut says we should suppress these entirely: 
<img width="889" alt="screen shot 2015-10-23 at 1 30 53 pm" src="https://cloud.githubusercontent.com/assets/682201/10700239/5b4444f4-798a-11e5-8e9c-cfb60d45d861.png">

**Comment by jonathandavis** [comment]
This is solved by the new screens system.

**Comment by clifgriffin** [comment]
@jonathandavis Yeah, we are probably now on this one. We can close.
