### ISSUE TITLE
Base of Operations Failure

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3405]
Base of Operations still shows States after choosing France, (drop down has no effect)

Unable to save

**Comment by sierrab123** [comment]
Nor does Target Markets work

**Comment by sierrab123** [comment]
I am getting this error from Firebug on the  settings page....
ReferenceError: sprintf is not defined
http://localhost/Shopp140/sp-scripts.js?load=shopp,setup,selectize&c=1&ver=46277de7fc4708b5752af364c40529e3
Line 6

**Comment by jonathandavis** [comment]
While under development, it is advised that you use `define('SCRIPT_DEBUG', true);` in `wp-config.php` when using `master`.

**Comment by jonathandavis** [comment]
The updated scripts need re-minified so the fixes are in the minified versions. This is a pre-release task.

**Comment by sierrab123** [comment]
This was caused in my case by the WAMP environment to a large extent. Whilst 1.3.9 ran fine 1.4 presents issues on localhost

**Comment by Just-m** [comment]
I think not being able to save base of operations was solved with this commit https://github.com/ingenesis/shopp/pull/3417 

Wasn't aware it had been reported already.

**Comment by sierrab123** [comment]
I set up an install on a local web matrix set up, a windows on-line server and an Apache server at GoDaddy.

All three locations gave the same result which was as follow

Master out of the box, no behaviors on set up page
Master with define('SCRIPT_DEBUG', true); added to wp-config, no behaviors on set up page
Master with minified files (Thanks Just Me) behaviors work on set up page

By behavior I am referring to the action/non-action of the Select All when choosing Target Markets

**Comment by sierrab123** [comment]
This issue is caused by Firefox, everything worked fine in Chrome.

**Comment by jonathandavis** [comment]
See #3433
