### ISSUE TITLE
The Tags menu under Catalog shows Categories

### ISSUE THREAD

**Issue by rickgregory** [ingenesis/shopp#3412]
In testing the 1.3.10 branch to see if it fixed an issue with categories, I found that I could now create and view categories. However, if I click the Tags menu, I see the Categories admin screen.

![screenshot 2015-12-10 22 34 26](https://cloud.githubusercontent.com/assets/1743922/11737451/39a77710-9f8e-11e5-963d-9c62e14cb90c.png)

**Comment by sierrab123** [comment]
I had no issues with this, both categories and Tags menu items delivered the correct page

**Comment by meredevelopment** [comment]
Hi, I'm not seeing this behaviour @rickgregory:
![image](https://cloud.githubusercontent.com/assets/3437528/11740240/0bd1a7e2-9fe9-11e5-9171-4ac98d08fadd.png)
- When you tried 1.3.10, how did you get the new files, is there a chance you missed one or two or was it via a clone / zip download?
- Do you have any other plugins that modify Shopp in any away, might be worth deactivating these as a test and reporting back.

Thanks!

**Comment by rickgregory** [comment]
Interesting. I grabbed the zip from the 1.3.x branch head. (https://github.com/ingenesis/shopp/tree/1.3.x). I'll retest with a clean db and default theme and report back

**Comment by rickgregory** [comment]
Sigh.  Downloaded the plugin off the commit link above and... all is well. Can't replicate even with t he plugins and themes so I have to assume something was messed up about the download I had last night. Sorry for the false alarm.

Closing.

**Comment by meredevelopment** [comment]
Thanks Rick, no idea but glad it's gone now, and thanks for testing!
