### ISSUE TITLE
Target Market Select All

### ISSUE THREAD

**Issue by Just-m** [ingenesis/shopp#3416]
This has probably always functioned this way but suddenly strikes me as odd.

When you check one country in the target market dropdown list on the settings page and save the settings, the dropdown menu will show the selected country at the top, then 'Select All', then the list of unchecked countries.

This 'put Select All after the checked and before the unchecked options' method results in a confusing dropdrown list when you use Select All. After that the 'Select All' option moves to the very end of the list making it seem like this action can not be undone other than manually.

I would prefer the 'Select All' option to stay at the top all the time.

**Comment by meredevelopment** [comment]
Yep I agree, this is confusing. Hopefully not a difficult fix? Let's see if it gets picked up as a job by someone :+1:

**Comment by jonathandavis** [comment]
I can understand the confusion it can cause. Priority-wise I see this as a nice to have but not critical.

**Comment by Just-m** [comment]
Yep, not critical at all. Just the first thing that confused me when clicking around on the settings page.

**Comment by meredevelopment** [comment]
On a fresh install of 1.4dev with WP4.4, this problem isn't present for me. Presumably it's been fixed since. Can you please confirm @Just-m if you still see it in 1.4dev?

**Comment by Just-m** [comment]
https://github.com/Just-m/shopp/commit/248f6bcf5170dea33435f6fba6411055603d4e8b
