### ISSUE TITLE
Orion Menu items on Settings page are adrift

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3418]
The Payments, Presentation, Pages, Images, Shipping rates and Shipping Boxes appear as blank screens on local and live sites after selecting them from the menu on the Settings page

**Comment by Just-m** [comment]
After making this change https://github.com/ingenesis/shopp/commit/e50d323ecb86b7eb8816e424a2a7de7e619e193e I have no blank pages. Not everything is functional but all show content. 

The only issue I see is 'Taxes' playing hide and seek when going through the menu options one by one.
