### ISSUE TITLE
On new Shopp install, saving permalinks required

### ISSUE THREAD

**Issue by clifgriffin** [ingenesis/shopp#3425]
I setup a brand new WP 4.4 / Shopp 1.3.10 install and found that until I manually re-saved permalinks, store pages (specifically product pages) 404'd. 

Guessing the same will be true on master but haven't tested yet.

**Comment by sierrab123** [comment]
I am finding the same with 1.4 dev,

**Comment by barryhughes** [comment]
Looks like the permalink flush was being 'deferred' until `init`, but `init` has actually already fired by the time the activation callback runs. Can someone review [PR/3428](https://github.com/ingenesis/shopp/pull/3482) and see if that helps here? Seems to resolve this on my end.

**Comment by clifgriffin** [comment]
Fixed in PR/3428.
