### ISSUE TITLE
Shopp update-Image, Shipping issues

### ISSUE THREAD

**Issue by thbennett** [ingenesis/shopp#3427]
I am in way over my head here and I don't know if I'm in the right place to ask for help. But I'm not finding help anywhere else. I updated Shopp, now images for products are not showing up. Also, when trying to get an estimate for shipping charges, getting shipping not available. I have followed instructions on Shopp to resolve the images issue, to go to permalinks and click update changes. Does not work. On shipping, I use UPS ground, which is selected and all required information for UPS, such as my access code, is in place. Please help this novice! 
www.GardensbyTeresa.com

**Comment by Just-m** [comment]
You should try the forum or the Help desk.

**Comment by thbennett** [comment]
I have been trying both the forum and the Help desk for 3-4 days, and have not gotten any response. Which is why I am searching here.

**Comment by Just-m** [comment]
Can you share links to those posts? Maybe they got stuck in cyberspace.

**Comment by thbennett** [comment]
One hour after posting and my post is on page 8!

https://wordpress.org/support/topic/shopp-update-images-and-shipping-not-working?replies=1

**Comment by Just-m** [comment]
I understand your frustration but the first post in that support sections explains pretty well that that is not our core Community Forum nor our Help desk https://wordpress.org/support/topic/shopp-support-on-wordpressorg

I thought you had left a message at 
- the forum https://shopplugin.net/support/forum/community-support/
- the Help desk https://shopplugin.net/support/

**Comment by thbennett** [comment]
I did leave a message at the help desk 4-5 days ago. Let's just complicate this a little more. I tried to log in, entered my email, was not recognized. Entered my username and requested a password. Said a password was sent, but it was not sent to me. My website was set up by a company that I no longer have contact with. I am just feeling stuck.

**Comment by Just-m** [comment]
What is your username on Shopp forum?

**Comment by thbennett** [comment]
terrihb

**Comment by Just-m** [comment]
There is no member with a username like that on Shopp Forum. I think you may be mixing WordPress.org and Shopplugin.net. Logging in to Shopplugin.net with your WordPress.org credentials will not work. I did find another post on wordpress.org on the same issue but in another section. You probably thought that to be a ticket to the helpdesk.

It could be your Shopp version was once bought by your webdeveloper and put in his/her name. This means they will receive the e-mail for resetting the password.

You should buy the Shopp support plugin and then contact the helpdesk or the community forum, or find a developer who can fix things for you.

Another thing to mention is, you said in a post on wordpress.org you didn't upgrade to WP4.4 yet. Shopp version 1.3.10 was released to work with WP4.4

Your request is not a core code related issue but a support question. Those are not valid here on GitHub. Therefor I will close this issue.
