### ISSUE TITLE
WordPress 4.4 and Shopp 1.3.10: An error occurred while submitting your order.

### ISSUE THREAD

**Issue by jeffleeismyhero** [ingenesis/shopp#3429]
I'm getting the following errors when using Shopp 1.3.10 with WordPress 4.4. This issue is also present when using the 1.3.x branch (commit 2d3a6f47fa9f5a52568a0f16e7cee2bb27a7d88a).

I've disabled all other plugins and removed caching and seo related plugins all together. That did not resolve the issue.

`WordPress - 4.4`
`Shopp - 1.3.10`
`Authorize.Net - 1.2.2`
`PHP - 5.3.3`
`Apache - 2.2.15`
`MySQL - 5.1`

After a long period of "Submitting..." the checkout page returns the following alert dialog. Upon clicking ok, the dialog disappears. If I click submit order again, I'm immediately taken to the "Thank you for your order" page. The order is processed and the charge is authorized for the card.

### Alert Dialog:
```
An error occurred while submitting your order. Please try submitting your order again.
```

### Apache Error Log:
```
[Sun Jan 03 02:39:03 2016] [error] [client 68.11.222.XXX] PHP Fatal error:  Call to undefined function shopp_error() in /var/www/production/domain.com/wp-content/plugins/shopp/storage/core/DBStorage.php on line 116, referer: http://www.domain.com/shop/page/2/
[Sun Jan 03 02:40:25 2016] [error] [client 174.69.149.XXX] PHP Notice: Could not save session updates to the database. ShoppErrors->php, trigger_error, ShoppSessionFramework->save, Shopping->resession, ShoppOrder->success, call_user_func_array, do_action_ref_array, OrderEventMessage->__construct, AuthedOrderEvent->__construct, OrderEvent->add, shopp_add_order_event, AuthorizeNet->sale, AuthorizeNet->process, call_user_func_array, do_action_ref_array, OrderEventMessage->__construct, OrderEvent->add, shopp_add_order_event, ShoppOrder->auth, call_user_func, ShoppOrder->process, call_user_func_array, do_action, ShoppOrder->purchase, call_user_func_array, do_action_ref_array, OrderEventMessage->__construct, OrderEvent->add, shopp_add_order_event, ShoppOrder->submit, call_user_func_array, do_action, ShoppCheckout->process, call_user_func_array, do_action, ShoppOrder->request, call_user_func_array, do_action_ref_array, WP->parse_request, WP->main, wp, require, referer: https://www.domain.com/shop/checkout/
[Sun Jan 03 02:43:40 2016] [error] [client 174.69.149.XXX] PHP Fatal error:  Maximum execution time of 500 seconds exceeded in /var/www/production/domain.com/wp-content/plugins/shopp/core/library/Session.php on line 449, referer: https://www.domain.com/shop/checkout/
[Sun Jan 03 02:43:40 2016] [error] [client 174.69.149.XXX] PHP Notice: Could not save session updates to the database. ShoppErrors->php, trigger_error, ShoppSessionFramework->save, call_user_func_array, do_action, shutdown_action_hook, referer: https://www.domain.com/shop/checkout/
```

**Comment by sierrab123** [comment]
This may be down to the 4.4 upgrade, I believe that WP are going to be releasing an update. I can see no other reports of this happening with Shopp and Authorize. You could try posting at the Shopp Help Desk (where a support team member can take a look at your site) or the Community forum

**Comment by dxdc** [comment]
@jeffleeismyhero I believe this is caused by a JS timeout on the order page. Can you try it using the default checkout template and/or confirm there are no errors in the JS console. This kind of scenario was responsible for my issues in the past.

**Comment by jeffleeismyhero** [comment]
There were/are no JS errors on the page and I don't see anything taking a long time to load. I ran optimize on all tables, updated the theme (though using 2015 didn't help so I doubt this did anything), created a new instance of the database in MySQL 5.6 and re-imported the database backup. The problem has not reoccurred since; however, it has not been thoroughly tested.

I will let you know if it creeps up again. Thanks for the help so far!
