### ISSUE TITLE
Newly added product images do not display in storefront or admin

### ISSUE THREAD

**Issue by butchler** [ingenesis/shopp#3438]
When I try to add product images when creating a new product or editing an existing product, the image thumbnails do not display in either the storefront or the admin interface. It shows the browser's broken image icon where the thumbnail should be.

However, previously added product images continue to display fine. I'm not sure which version the problem started with because both Wordpress and Shopp have been upgraded since then, but it should have started sometime in the last few months.

Looking at the request responses with Chrome's dev tools, it seems like it is returning a 200 OK response, but with no actual image data (Content-length is 0).

I am using Wordpress 4.4.1 and Shopp 1.3.10.

**Comment by Just-m** [comment]
This sounds more like a support request than a coding error. 
For support you can  use either the Community Forum or the Helpdesk at wwww.shopplugin.net

**Comment by butchler** [comment]
Oh okay, thank you. I'm sorry for the inconvenience.
