### ISSUE TITLE
Images and Details&Specs - unexpected loss

### ISSUE THREAD

**Issue by procka** [ingenesis/shopp#3439]
There is a strange behavior. On some products (randomly) there are unexpectable loss of Images and Details & Specs. One day is everything fine, next day the picture and details on some products are missing. Other product properties are ok (categories, description, price and so on).

It happened to older products but also to newly added products, so it is hard to find out any pattern which products are affected

**Comment by crunnells** [comment]
This sounds host related, either running out of memory or an under-powered DB server being overloaded. The very nature of it being random makes me think it's environment related, because we haven't seen any other reports of this kind of issue. I would be interested to know if you try the same setup on another server (locally, say) if you still experience the issue.

**Comment by procka** [comment]
I already switch from my own server to Media Temple and now using another local hosting company, so it was happening on 3 different hosting enviroments.

Size of the database right now is about 135 MB.

**Comment by msigley** [comment]
What version of shopp is the site running? It sounds like a caching issue at first glance and we made some fixes for cache compatibility in 1.3.10.

-----Original Message-----

**Comment by procka** [comment]
all the latest - WP 4.4.1 and Shopp 1.3.10

**Comment by msigley** [comment]
Never heard of zan cache pro. Try disabling it for now. Is this on traditional hosting or managed WordPress hosting? Managed WordPress hosting normally has caching you can tweak from the hosting dashboard.

What storage engine are you using in this site?

**Comment by procka** [comment]
https://zencache.com/ , but anyway, this issue is no related to this, because it already started before using the plugin.

The issue was happening on Mysql 5.1, but persist also when I moved to MariaDB 5.5, which is running now.

Actually, I already tried several possibilities with the hosting and database enviroment before I opened this ticket.

**Comment by msigley** [comment]
MariaDB is suspect to me. We had a previous incompatibility with it and pulling coverimages correctly but that should have been fixed in 1.3.10. But, I run MariaDB for my stores as well and haven't seen this issue. Do the images and specs disappear from both the customer facing pages and the WP admin?

**Comment by procka** [comment]
Yes, from both

**Comment by meredevelopment** [comment]
I'm experiencing very similar issues on one site. Still investigating but so far there seems to be no pattern to it. 

I wonder if this person, jettisoned recently, was having the same issue: #3438

**Comment by Just-m** [comment]
Does the information popup again randomly too, or once lost it never shows up again unless you re-enter it?

In other words, for the products that lost their information, is this information no longer present in the database? Is the error "the database loses data" or "Shopp not retrieving things correctly".

**Comment by procka** [comment]
Lost never shows up until I re-enter it manually. I never saw this messages...

**Comment by Just-m** [comment]
Did you check the database to see whether or not data is still there but somehow no longer linked to the product?

Either the database is losing data or Shopp (or other plugin) is doing weird things at some point when writing to the database.

Does it perhaps happen to products that have been ordered recently?

**Comment by procka** [comment]
I have checked, not easy to find the products on which it happens...Database is losing data, at least I could not find the information in the shopp_index table, I have looked several ways (type, date created product id ...)

It happend with no pattern, ussualy not to recently ordered product, but of course it also can happened.

**Comment by Just-m** [comment]
I was hoping you could find out whether the database is losing data on its own, or if Shopp is writing data the wrong way which makes it disappear.

Could even be related to a third party plugin that performs actions on Shopp data.
The only way to find out is by comparing database data before and after those actions.

**Comment by procka** [comment]
Hello guys, I finally figure out what is causing this problem - or at least it seems to be it.

The "Trash" is the problem, when I "delete permanently" the products from trash, I can clearly see that issue with missing pictures and details is occuring. 

The problem was bigger when I "Empty Trash" all at once, when I delete the same amount of products one by one, there were no so many loses, but still there were same.
