### ISSUE TITLE
Admin list inventory shows wrong value

### ISSUE THREAD

**Issue by ralphonz** [ingenesis/shopp#3441]
In the admin catalog list when viewing all products, the inventory number shown is not the same as the value shown in the inventory list and is not updated until the edit product page is visited.

**Comment by sierrab123** [comment]
Can confirm, the inventory report updates immediately whilst the admin product listing does not seem to.

The individual products are updated immediately on the product editor page but this is not carried over to the products listing page

**Comment by Just-m** [comment]
Can't replicate in 1.3.12
