### ISSUE TITLE
Error in shipping weight comparison using decimal comma

### ISSUE THREAD

**Issue by crunnells** [ingenesis/shopp#3443]
The shipping weight rate comparison function (in OrderWeight Tiers) compares decimal point weights against decimal comma notation weights (eg: 0.5 >= 0,5), resulting in unexpected shipping rate selection (apparently 0.02 >= 0,5 is true).

**Comment by jonathandavis** [comment]
Nice find!

**Comment by crunnells** [comment]
Fixed in https://github.com/ingenesis/shopp/commit/b4fb3b5cf0fc4918dc0d183fd9f4e2fcd1f16c25
