### ISSUE TITLE
1.3.10 issues with shipping/billing address

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3449]
Using a default theme, it looks as if Shopp is loading the shipping address in the first instance whether same shipping address is checked or not. It appears briefly and then disapears

**Comment by Just-m** [comment]
When the page loads quick enough there is less chance you will see this, but it is how it works. All information is present. TMK the page loads, after that javascript hides the shipping fields in case 'same shipping' is selected. 

Unselecting 'same shipping' will just remove the hide/hidden class from those fields to make them appear.
