### ISSUE TITLE
Scrambled order of countries in dropdown menus

### ISSUE THREAD

**Issue by clifgriffin** [ingenesis/shopp#3458]
The country order gets scrambled as countries are added and removed from the list under Setup. 

This is because Shopp consolidates the checked options at the top of the list. 

Argentina
Beliz
Chile
Zimbabwe

If all are selected at the same time, they countries will order A-Z.  If Zimbabwe is saved, and then the others are added, the order will be:
Zimbabwe
Argentina
Beliz
Chile

This gets really confusing for customers who are expecting their country to be represented in the correct order.

**Comment by jonathandavis** [comment]
We should continue to consolidate the selected countries. I do think we
need to sort the countries that are selected to maintain that order.

**Comment by clifgriffin** [comment]
@jonathandavis Yeah, the trick is how do we handle the special countries that are usually represented at the top? Ie, US, UK. 

Also, we need to keep Select Country at the top.  It seems to float around too :)

**Comment by clifgriffin** [comment]
I think this is the main root of the issue: https://github.com/ingenesis/shopp/commit/126911c43e0d7e669e3a767f6189f1a462180101

**Comment by clifgriffin** [comment]
Fixed in 78ed39b478f046ace2a581787af0e96cd39c1ff5. 

We'll tackle special sorting considerations (putting US / UK first) in another issue.

**Comment by msigley** [comment]
Drag and drop order of the countries please!

**Comment by clifgriffin** [comment]
@msigley Oof. Much easier to provide a filter.  I don't see much reason to provide that level of UI for something 99.9% of people wont' touch.

**Comment by jonathandavis** [comment]
No, I get what he's saying, but it should be a separate request. Basically,
rather than an algorithm order, allow people to drag country order around
so that merchants can set the order countries appear in the checkout menus.
