### ISSUE TITLE
Sort special countries first in target_markets setting. 

### ISSUE THREAD

**Issue by clifgriffin** [ingenesis/shopp#3459]
Should we sort US / UK / possibly other countries to the top of the list?

Or should we do it automatically based on the base country or something along those lines. Wondering if we should leave this to developers and make sure the right filters are available.

**Comment by sierrab123** [comment]
See https://github.com/ingenesis/shopp/pull/3460 and https://github.com/ingenesis/shopp/issues/2878

**Comment by jonathandavis** [comment]
Dependent on #2878

**Comment by jonathandavis** [comment]
This is addressed by the "Sort Alphabetically" and "Sort by Region" buttons.
