### ISSUE TITLE
Orion: Region/States box appearing in Base of Op for countries with no such list

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3477]
http://awesomescreenshot.com/0415opbha2

To recreate, choose a country such as France, the box appears.

Tested in Firefox and Chrome

**Comment by jonathandavis** [comment]
It is greyed out and disabled intentionally.

**Comment by sierrab123** [comment]
In 1.3.10 it looked better http://awesomescreenshot.com/0875opdq23

No sign of the box at all

**Comment by sierrab123** [comment]
Comparing the code of 1.3.10 with the 1.4 and think that the .hide() and .show() are missing from setup.js

**Comment by jonathandavis** [comment]
I know, it seems that simple, but it's not. There is a proxy object now that we didn't used to have.
