### ISSUE TITLE
Adding auto recalculation to cart page

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3487]
Currently, you have to click on the update button to fire a recalculation. It would be good if this recalculation could be fired automatically. 

There are instances where a customer skips the cart page and arrives at the checkout page "zipless", there is a case for adding auto recalculation to this page as well. There are however a lot of options that can change on this page and I am not sure how easy (or desirable) that would be to do

**Comment by dxdc** [comment]
I've added this to my store via some simple jQuery:

I have code to engage this via a WP plugin as well using the `if (is_cart_page()) {` functionality to load this via wp_enqueue_script. Let me know if you want more details:

```
jQuery(document).ready(function($) {
    $("#shopp div.qty-cart input").bind('change', function() {
        $("input#update-shopping").click();
    });
});
```

**Comment by sierrab123** [comment]
Love them, could you add it as a PR to the 1.3.12 dev branch?

**Comment by dxdc** [comment]
Done
