### ISSUE TITLE
Master, Error on selecting Categories

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3491]
In Shopp Admin, on selecting categories. The following error is returned:-

Fatal error: Call to a member function filter() on a non-object in C:\Users\Steve\Documents\My Web Sites\MasterfulShopping\wp-includes\taxonomy.php on line 805

Master includes all commits up until and including 17/03/16

**Comment by sierrab123** [comment]
@barryhughes  the first fix does get rid of the fatal error, but when I applied the second (which I actually tried first) I received a fatal error. Caused possibly by the fact that I had not applied the first one?? Maybe I need to manually apply the second rather than copy and overwrite.

**Comment by jonathandavis** [comment]
Fixed with #3616
