### ISSUE TITLE
Master, Error on Product page after saving new product

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3492]
Create a new product with image, variations and add-ons. On Save with Continue Editing in the dropdown, the page reloads with a deformed page with very little info showing.

However if you return to the page from Products listing, the page is fine with all info intact

**Comment by sierrab123** [comment]
The problem persists even with new product in the dropdown as the problem that @cliggriffin noted with categories exists in products also, with the dropdown (worklist) not functioning.

**Comment by sierrab123** [comment]
Barry's fix does indeed fix the issue of the deformed page but still leaves the work list issue in place

**Comment by barryhughes** [comment]
Yeah the only thing my fix was addressing was a problem where `$Product->images` contains one or more strings in addition to the expected image objects (which was triggering a fatal when it tried to access object properties for those strings) ... definitely not a complete solution to everything you listed.

**Comment by jonathandavis** [comment]
Fixed in fixes/orion-alpha branch.

**Comment by jonathandavis** [comment]
Fixed in master
