### ISSUE TITLE
Shopp Server down

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3523]
The Shopp site is down, resulting in time-outs on Shopp sites

As a workaround move the Shopp support plugin to a temporary folder

**Comment by ben72** [comment]
Just to clarify. The easiest is to just rename the directory /wp-content/shopp-support to for instance /wp-content/shopp-support-

**Comment by crunnells** [comment]
Or just uninstall it permanently 😁

**Comment by AlbertBoddema** [comment]
'Nice' a support plugin to create problems....
I had to open an support ticket at my webhost to get my sites running again.

**Comment by jonathandavis** [comment]
Resolved
