### ISSUE TITLE
1.3.11: Incorrect 'jump' var name for pagination?

### ISSUE THREAD

**Issue by meredevelopment** [ingenesis/shopp#3526]
Hi @Just-m I think 'jump' should be 'jumps' in api/theme/collection.php as you're using $jumps in the code right? (https://github.com/ingenesis/shopp/commit/a39b1fcd9d30cc65972a6a2ff2e958e0071e5647#diff-90a24f3aa0b5a2e8fbb497af809f342bR876)

Cheers!

**Comment by Just-m** [comment]
Your are mixing two variables with almost the same name.
$jumps is a calculated value that sets the step size when using the feature to step through pages other than one by one.
$jump is a setting to define whether or not to use the formentioned step through feature. When set to false there will be no link attached to the symbol or in case of default to the '...'

**Comment by meredevelopment** [comment]
Ok sorry, i see now. I was comparing it to some pagination work Matt and I did, that hasn't been merged in here. Not comparing like for like. sorry to waste your time!

**Comment by Just-m** [comment]
We could rename $jumps to $jumpsize.

In that case $jump is false or true, $jumpsize is a number the program calculates.

**Comment by meredevelopment** [comment]
Sorted by @Just-m in PR https://github.com/ingenesis/shopp/pull/3528
