### ISSUE TITLE
Events on payment method get fired multiple times

### ISSUE THREAD

**Issue by teufelmartin** [ingenesis/shopp#3580]
Hi,

we have activated two times offline payments. 
Once for invoice and second time for payment by installments.

When i click on mark payment as payed offline payment method event is fired twice.

This issue is already marked as a bug through the support team on shopplugin.net

**Comment by Just-m** [comment]
Just for testing, can you backup your database and files and then make this change to core/model/Gateway.php and check if it works correctly?

replace the existing `function activated()` with this

```php
    /**
     * Determines the activated gateway modules
     *
     * @author Jonathan Davis
     * @since 1.1
     *
     * @return array List of module names for the activated modules
     **/
    public function activated () {
        $Shopp           = Shopp::object();
        $this->activated = array();
        $gateways        = explode(',', shopp_setting('active_gateways'));
        $modules         = array_keys($this->modules);
        foreach ( $gateways as $gateway ) {
            $moduleclass = $this->moduleclass($gateway);
            if ( ! empty($moduleclass) )
                $this->activated[] = $moduleclass;
        }
        
        $test = array_unique($this->activated);
        $this->activated = $test;
        return $this->activated;
    }
```

Also check if all set Offline payment options are still present on checkout and in the Payment editor screen. It is a minor code change but still, don't forget to backup your files and data.

**Comment by clifgriffin** [comment]
@Just-m Very interesting. Can you explain better how this change works? 

Thanks!

**Comment by Just-m** [comment]
Even when multiple ShoppOffline payment instances have been set, they all use the same gateway, it is just that their labels and instructions differ. To determine the existance of multiple instances you need active gateways to be stored like ShoppOffline-0, ShoppOffline-1 and so on. But when it comes to checking which gateway is been used (and should be reacting to an order event) you only need ShoppOffline one time as all instances relate to this one ShoppOffline gateway.

All that changed in my test code is removing duplicate occurances of gateways. The original code loops through the activated gateways and `$this->moduleclass()` turns every ShoppOffline-x into ShoppOffline resulting in duplicates of the same gateway, resulting in firing the same order event more than once.

**Comment by teufelmartin** [comment]
@Just-m: Just wanna to let you know that your change works as expected.

**Comment by Just-m** [comment]
solved with commit https://github.com/ingenesis/shopp/pull/3581/commits/9921fa9107b31e5f08affb2994d9985c25f993c1
