### ISSUE TITLE
1.3.11: shopp('storefront.category-list') and cats widget broken when used with dropdown 'off'.

### ISSUE THREAD

**Issue by meredevelopment** [ingenesis/shopp#3583]
[This commit](https://github.com/ingenesis/shopp/commit/ade6d38b5fc44bf300ea7c1e111984a677b4c9d7#diff-ae8b73f2801a7964d5ce04c4d8e1ddc8L1747) has broken [shopp('storefront.category-list')](https://shopplugin.net/api/storefront-category-list/) and the Shopp Categories Widget when used with the 'dropdown=off/false/0' option. 

`$href = shopp($category, 'get-url');` on [line 1746](https://github.com/ingenesis/shopp/blob/ade6d38b5fc44bf300ea7c1e111984a677b4c9d7/api/theme/storefront.php#L1746) returns nothing, so all category links go to the same page. They have an empty 'href' arg. 

Works fine in 1.3.10. Looking at Jon's reason for the 'fix', I'm not sure we can just roll-back. But this is a breaking change so needs to be fixed before 1.3.11 release I think?

An example of it broken:  https://breakspear.satellitecreative.com/shop/ (see cats and manufacturers lists on left sidebar)

**Comment by Just-m** [comment]
Changing that one line (1746) back to the original seems to make it work.

`$href = shopp($category, 'get-url');`
back to 
`$href = get_term_link($category);`

The cause is probably related to $category being a WP_Term Object, not a ShoppCollection Object.

**Comment by meredevelopment** [comment]
Thanks for testing / confirming that. I didn't completely understand @jonathandavis comments on the commit, so don't know what bad thing reverting might do?
