### ISSUE TITLE
1.3 Alllow back orders

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3590]
Allow back orders does not function without inventory disabled

**Comment by jonathandavis** [comment]
I don't understand this request. Is this a request to enable back ordered product inventory when the inventory system is disabled?

**Comment by sierrab123** [comment]
The opposite!!

With inventory enabled on the product, an inventory of zero and back orders enabled, there is no add to cart option on the product

However with inventory disabled, an inventory of zero and back orders enabled you can add to cart.

Unless I am missing something this is not how I imagine it should work
