### ISSUE TITLE
Incorrect shipping input check in Purchase API / ship_state()

### ISSUE THREAD

**Issue by meredevelopment** [ingenesis/shopp#3597]
In the [ship_state()](https://github.com/ingenesis/shopp/blob/1.3.11/api/theme/purchase.php#L1427-L1439) function in the Purchase API, I believe it should be checking `$O->shipstate > 2` and not `$O->state > 2` on [line 1429](https://github.com/ingenesis/shopp/blob/1.3.11/api/theme/purchase.php#L1429).

``` php
public static function ship_state ( $result, $options, $O ) {
    $state = esc_html($O->shipstate);
    if ( strlen( $O->state > 2 ) ) return $state; // LINE 1429
    $regions = Lookup::country_zones();

    if ( isset($regions[ $O->country ])) {
        $states = $regions[ $O->country ];
        if (isset($states[ $O->shipstate ]))
            return esc_html($states[ $O->shipstate ]);
    }
    return $state;
}
```

Agreed?

**Comment by Just-m** [comment]
I agree this code may contain a bug, but it is a different one.

I think it should be:
```php
public static function ship_state ( $result, $options, $O ) {
    $state = esc_html($O->shipstate);
    if ( strlen( $state > 2 ) ) return $state; // LINE 1429
    $regions = Lookup::country_zones();

    if ( isset($regions[ $O->country ])) {
        $states = $regions[ $O->country ];
        if (isset($states[ $O->shipstate ]))
            return esc_html($states[ $O->shipstate ]);
    }
    return $state;
}
```
What it (imho) does is:
- puts the value of `$O->shipstate`, while using `esc_html()`, in variable `$state`
- if `$state` has more than 2 characters, it is mostlikely the full name, which then is returned (no other actions needed)
- if it is 2 (or less) characters long, then the lookup process starts, searching countryzones, regions, states and returns that result if found.
- if nothing is found the `$state` value, generated in the first line, is returned.
