### ISSUE TITLE
category.pagination show option cannot exceed number of pages

### ISSUE THREAD

**Issue by clifgriffin** [ingenesis/shopp#3606]
When using:

``` php
<?php shopp('category','pagination',array('show'=>3,'label'=>"")); ?>
```

On a category with two pages, the output of paging links has these options:
-1
0
1
2

But only on page 2. Page 1 shows correctly.

**Comment by sierrab123** [comment]
if ( $O->pages > 1 ) {
            if ( $O->pages < $show ) $show = $O->pages; // This line is added
            if ( $O->pages > $show ) $visible_pages = $show + 2;
            else $visible_pages = $O->pages + 1;
            $jumpsize = ceil( $visible_pages / 2 );


File is  /api/theme/collection.php, line 916

Not I obviously!!
