### ISSUE TITLE
link on orders page list causes a Wordpress error

### ISSUE THREAD

**Issue by fshequin** [ingenesis/shopp#3609]
Greetings,

Shopp ecommerce plugin version 1.3.10

the link on the Orders page in the backend of Wordpress causes a Wordpress Error:

"Sorry, you are not allowed to access this page."

here is the link it's trying to get:

https://wildhivefarm.com/wp-admin/admin.php?page=shopp-orders&id=3

the link from the Recent Orders admin dashboard widget DOES work, but it's different:

https://wildhivefarm.com/wp-admin/admin.php?page=shoppgit-orders&id=3

and they are different.....this seems like a bug in 1.3.10

please advise how to fix this...

Kind Regards, Fred Shequine

**Comment by crunnells** [comment]
Strange, sounds like something specific to your installation (or the Shopp package you've installed). Specifically, where it's creating a shoppgit-orders page. My advice would be to backup your site and install Shopp 1.3.11 (preferably using the WordPress upgrader) and see if that resolves the issue.
