### ISSUE TITLE
wp_shopp_shopping table

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3621]
Since the 1.3.12 release, the db table seems to be growing at an alarming rate, mine is at 20 mb

**Comment by jonathandavis** [comment]
I'm investigating.

**Comment by sierrab123** [comment]
The fix does flush the table after 2/3 days, but still leaves the issue of some 5,000 lines being created every 2 or 3 days on a quiet site

**Comment by jonathandavis** [comment]
May be time for a new robot strategy.
