### ISSUE TITLE
1.3.12 load_downloads uses only wp-user-id

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3622]
Client updated to 1.3.12 and has an old system where formerly shopp users and wp users where different.
And that's exactly the problem know.

If he checks the downloads for a old user where wp-user-id not equal to customer there are no downloads available because in this case you should use the customer id from purchase table.

**Comment by teufelmartin** [comment]
Any news on this bug?

**Comment by Just-m** [comment]
solved by ommit #3631

**Comment by teufelmartin** [comment]
Hi Just-m,

your commit didn't fixed the issue.
Old customers still have no download, because user id is empty

**Comment by Just-m** [comment]
There are a few commits in several files involved in solving this issue, I wonder if you applied them all.

If you have a test environment try using the most recent 1.3.x copies of the following files:
core/library/DB.php
core/model/Purchase.php
core/model/Purchased.php
core/flow/Registration.php

or download the whole 1.3.x branch (dev)

**Comment by teufelmartin** [comment]
Thank you,

now it's working!

**Comment by Just-m** [comment]
Great! Glad to be of help.
