### ISSUE TITLE
Account widget and SSL

### ISSUE THREAD

**Issue by AlbertBoddema** [ingenesis/shopp#3629]
We are testing to move to a HTTP/2 server.
All links have to be secure but the Account widget is pointing to a http link.

This is the error;
Mixed Content: The page at 'https://www.leomusic.nl/' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://www.leomusic.nl/shop/account/?acct'. This endpoint should be made available over a secure connection.

A tempory solution is changing customer.url in the login.php &  login-recover.php  template to the actual url with https. ( Thanks Ben for this solution)

**Comment by Just-m** [comment]
The 'secure' status of the website at this moment seems to be determined by whether or not any of the payment add-ons needs a secure environment.

If you add this line in /core/model/Payments.php at line 93
```php
if ( is_ssl() ) $this->secure = true;
```
it should work correctly. Could you check that?
I do not have an SSL website to test it with.

**Comment by Just-m** [comment]
After testing it appeared it needed fixing in another file.
