### ISSUE TITLE
Shopp Support plugin and PHP 7

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3630]
This is the error when activating the support plugin;
Fatal error: Uncaught Error: Call to undefined function mysql_get_server_info() in /var/hpwsites/u_lmusic/website/html/webroot/wp-content/plugins/shopp-support/Updates.php:62 Stack trace: #0 /var/hpwsites/u_lmusic/website/html/webroot/wp-includes/class-wp-hook.php(298): ShoppSupportUpdates::check('') #1 /var/hpwsites/u_lmusic/website/html/webroot/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #2 /var/hpwsites/u_lmusic/website/html/webroot/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /var/hpwsites/u_lmusic/website/html/webroot/wp-admin/admin.php(329): do_action('load-plugins.ph...') #4 /var/hpwsites/u_lmusic/website/html/webroot/wp-admin/plugins.php(10): require_once('/var/hpwsites/u...') #5 {main} thrown in /var/hpwsites/u_lmusic/website/html/webroot/wp-content/plugins/shopp-support/Updates.php on line 62

NB mysql_get_server_info — Get MySQL server info. This extension was deprecated in PHP 5.5.0, and it was removed in PHP 7.0.0

The above is from a HD ticket

**Comment by AlbertBoddema** [comment]
Changing Updates.php on line 62
fmysql_get_server_info to mysqli_get_server_info does solve the problem

**Comment by jonathandavis** [comment]
Interesting. This would be a relatively easy fix with refactored sDB structure that supports multiple DB engines.

**Comment by sierrab123** [comment]
@jonathandavis 
Any sign of a move on this?

**Comment by bobalbert** [comment]
your core db library is also outdated!
wp-content/plugins/shopp/core/library/DB.php

Come on... mysqli has been out since 5.0... do the search and replace and release 1.3.13 today

**Comment by Just-m** [comment]
To my knowledge DB.php is, and has been, well prepared for mysqli and PHP7.
But if we missed something, please let us know and we will update it.
The mysql code you find is just a fallback for installations that do not use mysqli.

The original poster was referring to the Support plugin, not the Core Shopp code.

**Comment by bobalbert** [comment]
yes my mistake. sorry about that

i didn't see you have both versions in the plugin

**Comment by AlbertBoddema** [comment]
Is this problem solved?

**Comment by sierrab123** [comment]
Looks like it, but cannot confirm.

**Comment by sierrab123** [comment]
Jut had another ticket on the HD re the issue with the support plugin and PHP 7, same fault as above.

**Comment by jonathandavis** [comment]
Fixed in Shopp+Support 1.0.1. Please login to your account at https://shopplugin.net/account and re-download the Shopp+Support plugin.
