### ISSUE TITLE
WordPress 4.7.1 breaks Manual Processing

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3632]
Decryption does not occur.

Reverting to WP 4.6 "fixes" the issue

**Comment by dxdc** [comment]
Did you check my PR? Wonder if it's related @sierrab123 

https://github.com/ingenesis/shopp/pull/3627

**Comment by Just-m** [comment]
https://github.com/ingenesis/shopp/pull/3627

**Comment by sierrab123** [comment]
Issue may be in fact caused by using old PHP (ver 5,4) no longer an issue with WP version, so closing
