### ISSUE TITLE
Refactor shopp('product.out_of_stock') to display correct 'out of stock' text

### ISSUE THREAD

**Issue by jonathandavis** [ingenesis/shopp#3724]
Merge changes from:

- https://github.com/ingenesis/shopp/commit/ce8f8c37600689e7fcedccfb888c9fcbc3d55fad

**Comment by jonathandavis** [comment]
I believe these changes regress previous functionality, especially for the default use case. This change would break installs that try to use `if( shopp('product.out-of-stock') ) { … }`.

**Comment by apple-web-evangelist** [comment]
Based on discussion we're not taking these changes into `master`.

**Comment by jonathandavis** [comment]
Based on discussion in Slack, we're not going to take these changes into `master`.
