### ISSUE TITLE
Merge updated PayPal endpoints

### ISSUE THREAD

**Issue by jonathandavis** [ingenesis/shopp#3737]
Merge changes from:

- https://github.com/ingenesis/shopp/commit/d28cc10b6217b32b0cc52015ba6c5beb9f45177b

**Comment by jonathandavis** [comment]
See the comments added to the linked commit above.

**Comment by sierrab123** [comment]
This was the subject of much discussion. However in correspondence with PayPal, which I may still have, they were insistent that the ip url was deprecated on I think March 30 and that the correct url was the one we have now

This can be tested by trying to make a payment, you will find a failure results when using the one suggested in the docs

**Comment by sierrab123** [comment]
There is a full discussion in Slack on April 26. Here is the email I received from PP

Thank you for getting back to me.

Recently there was a change to the way PayPal Payments Standard checkout flows are handled:

https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ2067&expand=true&locale=en_US

Non standard endpoints that were causing a fall back to the old checkout flow were shut off on March 30, 2017.

Also there were some variables that were deprecated as well:

https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/#deprecated-variables

The site seems to be redirecting to the correct URL right now.

Thank you and have a wonderful day!

Sincerely,

If you check that discussion on Slack you will see comments from Yvonne, Clif and Chris

**Comment by jonathandavis** [comment]
None of the response that you got from PayPal address these endpoints. The paypal-knowledge URL article does **not** mention any of the endpoints we were using.


This documentation lists the `ipnpb.` prefix instead:
https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNImplementation/

This document suggests that they are moving from `www` to `ipnpb` going forward:
https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=faq1916&viewlocale=en_us

Seems like we should be using `ipnpb.paypal.com` endpoints.

**Comment by sierrab123** [comment]
Using ipndb.paypal.com gives you this https://puu.sh/wku78/0dee5c783f.png

The email that was received from PP did in fact reference the correct points. The ones that were being tested were ipndb (the same ones that get the faulty response). I had switched back to the regular ones in Shopp which worked and she said that was correct

For testing this morning I first ran the tests with the ones in place, all was good

I updated the site using your overnight commits and received the above screenshot which is exactly what happened in early April

**Comment by jonathandavis** [comment]
ok we can revert.
