### ISSUE TITLE
Merge use business name on receipt/email instead of blogname

### ISSUE THREAD

**Issue by Just-m** [ingenesis/shopp#3758]
https://github.com/ingenesis/shopp/commit/48eed01192dc71d32c1fd0222b785ef9a8945a31
https://github.com/ingenesis/shopp/commit/4f8cd794ad8622babfe69e178ac69cd0e1482940
https://github.com/ingenesis/shopp/commit/4a8377883b11d8880d658614886f407e9bb9e42d
https://github.com/ingenesis/shopp/commit/93da477d463067610dc2489420a5338e76653e40

**Comment by jonathandavis** [comment]
93da477 needs to be a separate effort.
