### ISSUE TITLE
Merge check for new Customer before Shipping/Billing adjustment

### ISSUE THREAD

**Issue by Just-m** [ingenesis/shopp#3769]
1.3.x - /core/flow/Account.php (line 392)

not sure where this code went and if it is still needed

https://github.com/ingenesis/shopp/commit/6511274a42e947a283a5c3f3d38120ea3f3c262d

**Comment by jonathandavis** [comment]
This change is tricky. I need to understand what the issue was it was trying to solve.

**Comment by jonathandavis** [comment]
The new location for this code is under `core/screens/Customers.php` within the `ShoppScreenCustomerEditor` class in the `layout()` method. You could accomplish the "new" check using the new `$this->request('new')` property.

**Comment by Just-m** [comment]
Maybe not needed any more. When you created a new customer in Admin, the log showed errors/warnings on data that is not present for new customers, like purchase data. Added the `$new_customer` variable to be able to skip the query for/use of the not present data.

**Comment by jonathandavis** [comment]
I'm confirming this no longer appears to be an issue in the new screen controller.
