### ISSUE TITLE
Merge Setting to enable/disable imageserver use through adminpanel

### ISSUE THREAD

**Issue by Just-m** [ingenesis/shopp#3771]
core/library/Shopp.php

https://github.com/ingenesis/shopp/blob/master/core/library/Shopp.php#L339

https://github.com/ingenesis/shopp/commit/856d3077dfff4a4a0c27c8a56959811ea55efd8e

core/ui/settings/Advanced.php
https://github.com/ingenesis/shopp/commit/538212a2ab6a3101fe253349c8ab06f79d0988c7

**Comment by jonathandavis** [comment]
Why was this added? This seems bad and needs more discussion.

**Comment by jonathandavis** [comment]
The new ShoppServices approach in Orion make this unnecessary. If there are residual issues going forward, we should solve the underlying problems.
