### ISSUE TITLE
Merge prevent database errormessage

### ISSUE THREAD

**Issue by Just-m** [ingenesis/shopp#3772]
https://github.com/ingenesis/shopp/blob/master/core/library/DB.php#L445

https://github.com/ingenesis/shopp/commit/856d3077dfff4a4a0c27c8a56959811ea55efd8e

**Comment by jonathandavis** [comment]
What was the error message? This change is very concerning. It can tank servers in low memory environments.

**Comment by Just-m** [comment]
this line
-		// Free the results immediately to save memory
-		$db->api->free();
resulted in errormessage `'Could not fetch mysqli_result'`
that is why a check was added
`if ( isset($db->found) && $db->found > 0 ) $db->api->free();`

**Comment by jonathandavis** [comment]
That makes a lot more sense.
