### ISSUE TITLE
Fatal Error Orion with PHP 7.1

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3796]
New Install on 7.1

New product: On saving:-

[23-May-2017 13:36:08 UTC] PHP Fatal error:  Uncaught Error: Call to a member function resizing() on string in C:\wamp64\www\devshopp\wp-content\plugins\shopp\core\ui\products\images.php:6
Stack trace:
#0 C:\wamp64\www\devshopp\wp-content\plugins\shopp\core\library\UI.php(70): include()
#1 C:\wamp64\www\devshopp\wp-admin\includes\template.php(1048): ShoppAdminMetabox->box(Object(ShoppProduct), Array)
#2 C:\wamp64\www\devshopp\wp-content\plugins\shopp\core\ui\products\editor.php(66): do_meta_boxes(Object(WP_Screen), 'normal', Object(ShoppProduct))
#3 C:\wamp64\www\devshopp\wp-content\plugins\shopp\core\screens\Products.php(694): include('C:\\wamp64\\www\\d...')
#4 C:\wamp64\www\devshopp\wp-content\plugins\shopp\core\flow\Admin.php(345): ShoppScreenProductEditor->screen()
#5 C:\wamp64\www\devshopp\wp-content\plugins\shopp\core\flow\Admin.php(90): ShoppAdminController->screen()
#6 C:\wamp64\www\devshopp\wp-includes\class-wp-hook.php(298): ShoppAdmin->route('')
#7 C:\wamp64\www\devshopp\wp-includes\class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) in C:\wamp64\www\devshopp\wp-content\plugins\shopp\core\ui\products\images.php on line 6
[23-May-2017 13:36:08 UTC] PHP Fatal error:  Uncaught Error: Class 'ImageServer' not found in C:\wamp64\www\devshopp\wp-content\plugins\shopp\services\image.php:234
Stack trace:
#0 C:\wamp64\www\devshopp\wp-content\plugins\shopp\services\image.php(58): ShoppImageServer->error()
#1 C:\wamp64\www\devshopp\wp-content\plugins\shopp\services\image.php(22): ShoppImageServer->__construct()
#2 C:\wamp64\www\devshopp\wp-content\plugins\shopp\core\library\ShoppServices.php(88): require('C:\\wamp64\\www\\d...')
#3 C:\wamp64\www\devshopp\wp-content\plugins\shopp\core\library\Shopp.php(378): ShoppServices::serve()
#4 C:\wamp64\www\devshopp\wp-content\plugins\shopp\Shopp.php(38): Shopp::services()
#5 C:\wamp64\www\devshopp\wp-settings.php(304): include_once('C:\\wamp64\\www\\d...')
#6 C:\wamp64\www\devshopp\wp-config.php(89): require_once('C:\\wamp64\\www\\d...')
#7 C:\wamp64\www\devshopp\wp-load.php(37): require_once('C:\\wamp64\\www\\d...')
#8 C:\wamp64\www\devshopp\wp-admin\admin.php(31): require_once('C:\\wamp64\\www\\d...')
#9 {main}
  thrown in C:\wamp64\www\devshopp\wp-content\plugins\shopp\services\image.php on line 234
[23-May-2017 13:37:44 UTC] Shopp: Session started ----------------------------------------------------------------

[23-May-2017 13:37:45 UTC] PHP Fatal error:  Uncaught Error: Call to a member function resizing() on string in C:\wamp64\www\devshopp\wp-content\plugins\shopp\core\ui\products\images.php:6
Stack trace:
#0 C:\wamp64\www\devshopp\wp-content\plugins\shopp\core\library\UI.php(70): include()
#1 C:\wamp64\www\devshopp\wp-admin\includes\template.php(1048): ShoppAdminMetabox->box(Object(ShoppProduct), Array)
#2 C:\wamp64\www\devshopp\wp-content\plugins\shopp\core\ui\products\editor.php(66): do_meta_boxes(Object(WP_Screen), 'normal', Object(ShoppProduct))
#3 C:\wamp64\www\devshopp\wp-content\plugins\shopp\core\screens\Products.php(694): include('C:\\wamp64\\www\\d...')
#4 C:\wamp64\www\devshopp\wp-content\plugins\shopp\core\flow\Admin.php(345): ShoppScreenProductEditor->screen()
#5 C:\wamp64\www\devshopp\wp-content\plugins\shopp\core\flow\Admin.php(90): ShoppAdminController->screen()
#6 C:\wamp64\www\devshopp\wp-includes\class-wp-hook.php(298): ShoppAdmin->route('')
#7 C:\wamp64\www\devshopp\wp-includes\class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) in C:\wamp64\www\devshopp\wp-content\plugins\shopp\core\ui\products\images.php on line 6

[23-May-2017 13:37:46 UTC] PHP Fatal error:  Uncaught Error: Class 'ImageServer' not found in C:\wamp64\www\devshopp\wp-content\plugins\shopp\services\image.php:234
Stack trace:
#0 C:\wamp64\www\devshopp\wp-content\plugins\shopp\services\image.php(58): ShoppImageServer->error()
#1 C:\wamp64\www\devshopp\wp-content\plugins\shopp\services\image.php(22): ShoppImageServer->__construct()
#2 C:\wamp64\www\devshopp\wp-content\plugins\shopp\core\library\ShoppServices.php(88): require('C:\\wamp64\\www\\d...')
#3 C:\wamp64\www\devshopp\wp-content\plugins\shopp\core\library\Shopp.php(378): ShoppServices::serve()
#4 C:\wamp64\www\devshopp\wp-content\plugins\shopp\Shopp.php(38): Shopp::services()
#5 C:\wamp64\www\devshopp\wp-settings.php(304): include_once('C:\\wamp64\\www\\d...')
#6 C:\wamp64\www\devshopp\wp-config.php(89): require_once('C:\\wamp64\\www\\d...')
#7 C:\wamp64\www\devshopp\wp-load.php(37): require_once('C:\\wamp64\\www\\d...')
#8 C:\wamp64\www\devshopp\wp-admin\admin.php(31): require_once('C:\\wamp64\\www\\d...')
#9 {main}
  thrown in C:\wamp64\www\devshopp\wp-content\plugins\shopp\services\image.php on line 234

On reverting to PHP 7.0 the product does show in the catalog listing, however the product page itself shows only the product name and image and not the variations or add-ons.

THe catalog listing does show the variation as does the product page in the store, although the image is missing from that, caused by the old problem of pretty permalinks.

**Comment by sierrab123** [comment]
On another fresh install, after
saving product I am seeing this on the product editor page https://puu.sh/vZUh8/f8a47bdbe1.png.

In addition Advanced setting page is blank

**Comment by jonathandavis** [comment]
I have the patch, but I think this needs more investigation as to why the `$Product->images` array includes an entry with the product image ID:

```php
$Product->images[0] = 97;
```

It should simply include the `ProductImage` entry:

```php
$Product->images[97] = ProductImage {…};
```

**Comment by sierrab123** [comment]
Patch works, but still leaves the longstanding issue of images not showing in the store until you comment out the shopp images line in htaccess

**Comment by sierrab123** [comment]
On 2 fresh installs, I am seeing the same issue re products

After creating a new product I can see the slug  http://www.sierrab123.nl/shop/aroma/ which is fine, but upon re-saving it becomes  http://www.sierrab123.nl/shop/aroma-2/. On the next save it reverts to  http://www.sierrab123.nl/shop/aroma/ and then back to  http://www.sierrab123.nl/shop/aroma-2/
