### ISSUE TITLE
Flash Uploader Shopp 1313

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3818]
With the Flash loader enabled, a black bar is shown below the add image and it is not possible to upload multiple images

**Comment by sierrab123** [comment]
With WP 4.9, the black bar seems to have gone, but it still is not possible to upload multiple images

**Comment by meredevelopment** [comment]
Was it making use of SWFUpload? If so it's gooooone: https://core.trac.wordpress.org/ticket/41752

**Comment by sierrab123** [comment]
Bummer

**Comment by crunnells** [comment]
I hear Plupload is the recommended replacement: http://www.plupload.com/

**Comment by sierrab123** [comment]
The issue has been resolved in the Master dropzone branch and will be backported to the next release

**Comment by jonathandavis** [comment]
Closed with 339d1085526a9e276c81e7331b15af794d0cfc0f (and several other changes) in 1.4 branch.
