### ISSUE TITLE
Stripe Warning

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3819]
This appears on the checkout page on submission

"Sending credit card numbers directly to the Stripe API is generally unsafe. To continue processing use Stripe.js, the Stripe mobile bindings, or Stripe Elements. For more information, see https://dashboard.stripe.com/account/integration/settings."

**Comment by dxdc** [comment]
@sierrab123 @jonathandavis I fixed this a while ago. It requires some changes to the core code. You can have a look at the Stripe-specific aspects.

https://github.com/dxdc/Shopp-Advanced-Validation/tree/master/shopp-advanced-validation

**Comment by sierrab123** [comment]
Fixed

**Comment by dxdc** [comment]
@sierrab123 any chance I could have a look at the latest commits for this (incl to Stripe API) to include for my version?

**Comment by sierrab123** [comment]
Ask Jonathan, I am afraid I don't have them

**Comment by dxdc** [comment]
thx @sierrab123 .. @jonathandavis would appreciate it if you can share those details with me! I'd also be curious to see how this was embedded in the core code.

**Comment by sierrab123** [comment]
Dan, it's all the gateway, no changes in core

**Comment by dxdc** [comment]
How is that possible? The token must be fetched client side without CC data being sent to the server.
