### ISSUE TITLE
Strange calculations on 1.4 dev

### ISSUE THREAD

**Issue by AlbertBoddema** [ingenesis/shopp#3825]
To day I took a quick look at dev version and when I look at my olders invoices there are some calculation issues.
![afbeelding](https://user-images.githubusercontent.com/4806294/35649871-a4d13688-06da-11e8-94c7-6a4366d5f065.png)

**Comment by sierrab123** [comment]
@AlbertBoddema 

How old was that invoice?

Interesting

With new invoices it works fine

**Comment by AlbertBoddema** [comment]
Hi,

I mean by old invoices made with version 1.3.12 or earlier NB invoices made in 2014 and older are correct.
Also ther is someting strange with the sorting of te invoice numbers lower as 10.
![afbeelding](https://user-images.githubusercontent.com/4806294/35705470-c84359fc-07a2-11e8-9cc7-7e2fdb49f504.png)

**Comment by AlbertBoddema** [comment]
Also the problem is here with an new testorder made in 1.4.
![afbeelding](https://user-images.githubusercontent.com/4806294/35705712-8980c3e8-07a3-11e8-8b26-63ba579aa86d.png)

**Comment by sierrab123** [comment]
Albert, It looks as if you have some custom code in place as I have just tested and cannot recreate any of your results

Try with default theme and no other plugins or customisations

**Comment by AlbertBoddema** [comment]
Hi Sierab,
Shopp is the only active plugin
The theme is twenty-twelve.

I just noticed this behavior;
When you start loading the the page everyting is ok 
When the page is loaded completed the values change, looks like a script kicks in...

**Comment by AlbertBoddema** [comment]
![afbeelding](https://user-images.githubusercontent.com/4806294/35747824-19220586-084c-11e8-9a47-bb70bad66737.png)

**Comment by sierrab123** [comment]
Just to clarify, you are using the 1.4 branch, not the master. Is that correct? I am not seeing anything like you are.

Did you test on the demo site? http://sierrab123.nl/shopp1400/shop/shipping-product/ ?

**Comment by AlbertBoddema** [comment]
![afbeelding](https://user-images.githubusercontent.com/4806294/35750818-8d5f0ce6-0856-11e8-898a-5fbff6a06dc3.png)

**Comment by sierrab123** [comment]
Sadly that is the wrong one!!

It was correct but dev changed about a month ago and so that link is no longer correct

The 1.4dev you want is to be found at https://github.com/ingenesis/shopp/tree/1.4.x

That link you used is actually going to be 1.5dev (although I will note the fault when that is developed)

**Comment by AlbertBoddema** [comment]
Ok the problem is not present in this real 1.4.dev.
Sloppy to have wrong links..
