### ISSUE TITLE
Support page for customers on Shopp site reports error (but works)

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3839]
From Customer.....
"Also, for what it's worth, there is a strange "error-looking" box below this text-entry box for support. Starts "Strict standards: Non-static method DatabaseObject::tablename() should not be called statically, assuming $this from incompatible context in /srv/users/serverpilot/apps/shopp/public/wp-content/plugins/PrioritySupport/PrioritySupport.php on line 825" And then displays the call stack with a variety of php files and lines:
Time Memory Function Location

1 0.0002 271464 {main}( ) .../topic.php:0
2 0.1262 10589656 bb_load_template( ) .../topic.php:47
3 0.1289 10682432 include( '/srv/users/serverpilot/apps/shopp/public/support/my-templates/shopplugin/helpdesk/ticket.php' ) .../functions.bb-template.php:45
4 0.2516 10786632 post_form( ) .../ticket.php:70
5 0.2525 10789744 bb_load_template( ) .../functions.bb-template.php:299
6 0.2531 10811624 include( '/srv/users/serverpilot/apps/shopp/public/support/my-templates/shopplugin/helpdesk/reply-form.php' ) .../functions.bb-template.php:45
7 0.2548 10813424 do_action( ) .../reply-form.php:33
8 0.2548 10814856 call_user_func_array:{/srv/users/serverpilot/apps/shopp/public/support/bb-includes/backpress/functions.plugin-api.php:341} ( ) .../functions.plugin-api.php:341
9 0.2548 10814936 Priority->select_priority_ui( ) .../functions.plugin-api.php:341
10 0.2551 10815496 PrioritySupport->load_credits( ) .../priority.php:597

**Comment by sierrab123** [comment]
On Pending, there is another message
"

( ! )  Strict standards: mktime(): You should be using the time() function  instead in  /srv/users/serverpilot/apps/shopp/public/support/my-plugins/auto-close/auto-close.php  on line 29
--


1 | 0.0002 | 257312 | {main}(  ) | .../view.php:0
2 | 0.0005 | 288856 | require_once( '/srv/users/serverpilot/apps/shopp/public/support/bb-load.php' ) | .../view.php:2
3 | 0.0018 | 508928 | require_once( '/srv/users/serverpilot/apps/shopp/public/support/bb-settings.php' ) | .../bb-load.php:163
4 | 0.0985 | 10495728 | do_action(  ) | .../bb-settings.php:1201
5 | 0.5546 | 10772952 | call_user_func_array:{/srv/users/serverpilot/apps/shopp/public/support/bb-includes/backpress/functions.plugin-api.php:341} (  ) | .../functions.plugin-api.php:341
6 | 0.5546 | 10772984 | kill_stale_topics(  ) | .../functions.plugin-api.php:341
7 | 0.6475 | 10771752 | mktime (  ) | .../auto-close.php:29

**Comment by jonathandavis** [comment]
Fixed.
