### ISSUE TITLE
[feature-request] integration with MailChimp's E-commerce360

### ISSUE THREAD

**Issue by shopp-lighthouse-import** [ingenesis/shopp#530]
*Imported from Lighthouse* http://shopp.lighthouseapp.com/projects/47561/tickets/530
Reported by **Hiranthi** at **Sunday, 12-Sep-10 16:02:02 GMT-0400**

As the title says: integration with E-commerce360 of MailChimp (http://www.mailchimp.com/plugins/e-commerce-360/)

**Comment by crunnells** [comment]
@clifgriffin already has a plugin that handles this functionality. IMHO this falls straight into add-on territory, and does not need rolling into Shopp core.
