### ISSUE TITLE
Can't update customer shipping info for an order

### ISSUE THREAD

**Issue by shopp-lighthouse-import** [ingenesis/shopp#717]
_Imported from Lighthouse_ http://shopp.lighthouseapp.com/projects/47561/tickets/717
Reported by **brandondove** at **Saturday, 27-Nov-10 17:10:28 GMT-0500**

We had a couple orders come in that contained either incomplete or incorrect shipping information. The only way to edit shipping information is on the customer object. When updating the shipping information on the customer, it doesn't update the shipping information on the order. This seems like correct behavior because a customer could change their shipping information for each order (say if they were sending a present to a friend). The problem is that there is no way to update the shipping information on a per order basis.
###### Steps to Repeat
1. Submit a order with incorrect shipping information
2. Go to the admin order view
3. Click on the customer name to edit the customer
4. Edit the shipping information
5. Save.
   5a. Note the saved changes
6. Go back to the order
   6a. Note the original incorrect information
##### Environment

Web Browser: FF3
Server OS: Linux
Web Server: Apache
PHP version: 5.2.14
WordPress Version: 3.0.1
Shopp Version: 1.1.4.1

**Comment by Just-m** [comment]
Not sure since when, but it is possible to change shippingaddress of the order in 1.3.12
